### ISSUE TITLE
pyiceberg always return false for catalog.table_exists when used with Polaris catalog

### ISSUE THREAD

**Issue by djouallah** [apache/iceberg-python#1006]
### Apache Iceberg version

0.7.0 (latest release)

### Please describe the bug 🐞

cross posting here, as I am not sure, if it is a pyiceberg bug or polaris 

https://github.com/polaris-catalog/polaris/issues/96

**Comment by ndrluis** [comment]
Hello @djouallah, I did a test with the Tabular catalog and table_exists works as expected. So I believe this is a bug in the Polaris catalog.

**Comment by djouallah** [comment]
fwiw, it is working as expected, I presume polaris did fix it
