### ISSUE TITLE
contributing.md file is missing...

### ISSUE THREAD

**Issue by onemriganka** [apache/iceberg-python#101]
### Feature Request / Improvement

I THINK HAVING A CONTRIBUTING.MD FILE WILL HELP BEGINNERS TO CONTRIBUTE TO THIS PROJECT

**Comment by onemriganka** [comment]
attempted #101

**Comment by Fokko** [comment]
Hey @onemriganka Thanks for raising this. We have a contributing section on the docs: https://py.iceberg.apache.org/contributing/ Feel free to improve that in any way.
