### ISSUE TITLE
[feat] Run unit test in CI on pull request

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#1051]
### Feature Request / Improvement

It's easy to forget to add the "integration test mark" for integration tests. For example, [`test_table_scan_default_to_large_types`](https://github.com/apache/iceberg-python/blob/f05b1aedee8451d981188adf68be5e8b360a9ca1/tests/integration/test_reads.py#L755-L757) is currently missing the integration test mark since it depends on the hive catalog. 

We can solve this by running `make test` in CI. `make test` will fail for the above since the hive catalog is not available.

**Comment by sungwy** [comment]
Hi @kevinjqliu - I think this will result in `make test` being run twice in both `make test-coverage`, and in `make test` for all python versions. I'm wondering if there's a better way to solve this.

Would it make more sense to generate two separate coverage reports, and then combine them as a part of `make test-coverage`?

This way, we could generate the coverage reports for the unit tests first without the docker set up, set up the docker containers and then run the rest of the test suite

**Comment by sungwy** [comment]
Hi @Minfante377 and @youssef-itanii - thank you both for jumping onto this issue so quickly! Could we first discuss other options based on the comment above?

**Comment by youssef-itanii** [comment]
Hello 
Yes, I noticed that we would be running coverage tests and the tests, so we are running the tests twice. 
Do you mean generate test coverage for the unit tests and integration tests separately?

**Comment by sungwy** [comment]
Yes, maybe we could start with having separate make commands for generating coverage for unit tests, and then the integration tests. And then we could just have one that invokes the two in sequence

**Comment by Minfante377** [comment]
Hi. Sorry didn't realize that @youssef-itanii had already opened a PR for this. I think it happened almost simultaneously.
I think that splitting the commands make sense

**Comment by Minfante377** [comment]
Would something like this work?
https://github.com/apache/iceberg-python/pull/1055/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R81

**Comment by youssef-itanii** [comment]
yes, that's what I did, but I'm currently waiting for the workflow to end to see if the checks pass.

**Comment by Minfante377** [comment]
I noticed that the unit tests are failing at 90% coverage. They have 88% currently.

**Comment by youssef-itanii** [comment]
yes, but in the `make test` they didnt check for the % of coverage, so Im checking the % after combining

**Comment by youssef-itanii** [comment]
@sungwy my combining the coverage, do you mean combining the output, or just the commands that run the coverage tests? If it's the latter, then that saves me a lot of time :smiling_face_with_tear:

**Comment by sungwy** [comment]
I think it would be good to assert the coverage failure boundary on all tests instead of enforcing them on the unit and integration tests separately.

What I mean is:

If we set the `--data-file` argument for the `coverage run` to a specific value for the unit tests (`.coverage.unit`), and then a different one for the integration test (`.coverage.integration`), then we could `coverage combine` these data files and then produce the `coverage report` together.

So each commands will just `coverage run` and write the output to the specific coverage data files, and we can run the commands to combine and report the coverage together.

**Comment by youssef-itanii** [comment]
Would the coverage % still be 90% in this case?

**Comment by sungwy** [comment]
> Would the coverage % still be 90% in this case?

Yes, we should be able to keep the same failure threshold because we'd be reporting the coverage together across all the tests

**Comment by youssef-itanii** [comment]
The changes I made are pretty much done, I'm just checking this final test (taking quite a lot of time) to see if it is working and I will push to the current PR i made

**Comment by youssef-itanii** [comment]
@sungwy you can check out the changes in my [PR](https://github.com/apache/iceberg-python/pull/1054)

**Comment by sungwy** [comment]
Hi @youssef-itanii and @Minfante377 - thank you again for working on these PRs, and sorry for this unfortunate concurrency conflict. I think we could avoid a concurrency conflict in the future by first assigning a story to a potential solution contributor.

For this specific issue, I think it would make sense to move forward with @Minfante377 's PR as I think having a make command to run both actions is a good idea:

```
test-coverage: | test-coverage-unit test-coverage-integration
	poetry run coverage combine .coverage.unit .coverage.integration
```

**Comment by Minfante377** [comment]
Thank you @sungwy and @youssef-itanii . I'll remember to self assign the issue to me if I start working for a solution for an issue in the future.

**Comment by youssef-itanii** [comment]
> Hi @youssef-itanii and @Minfante377 - thank you again for working on these PRs, and sorry for this unfortunate concurrency conflict. I think we could avoid a concurrency conflict in the future by first assigning a story to a potential solution contributor.
> 
> For this specific issue, I think it would make sense to move forward with @Minfante377 's PR as I think having a make command to run both actions is a good idea:
> 
> ```
> test-coverage: | test-coverage-unit test-coverage-integration
> 	poetry run coverage combine .coverage.unit .coverage.integration
> ```

No problem! It was quite a learning experience :smile:  I'll make sure to self assign as well in the future!

**Comment by kevinjqliu** [comment]
> I think this change will result in make test being run twice in both make test-coverage, and in make test for all python versions. I'm wondering if there's a better way to solve this.

[`python-ci.yml` ](https://github.com/apache/iceberg-python/blob/main/.github/workflows/python-ci.yml#L52-L53) runs `make test-coverage`
[`python-integration.yml`](https://github.com/apache/iceberg-python/blob/main/.github/workflows/python-integration.yml#L42-L43) runs `make test-integration`
Both run on each pull request. 
I think the subtle difference is not having the docker container up while running unit tests. 

> This way, we could generate the coverage reports for the unit tests first without the docker set up, set up the docker containers and then run the rest of the test suite

+1

**Comment by kevinjqliu** [comment]
Thanks everyone for coming up with this solution, love the team work!!
