### ISSUE TITLE
Increase the minimal required pyarrow version to 14.0.0

### ISSUE THREAD

**Issue by ndrluis** [apache/iceberg-python#1089]
### Apache Iceberg version

0.7.1 (latest release)

### Please describe the bug 🐞

We use the promote_options argument in the concat_tables method, which is supported only in versions 14.0 or higher.

https://arrow.apache.org/docs/14.0/python/generated/pyarrow.concat_tables.html
https://arrow.apache.org/docs/13.0/python/generated/pyarrow.concat_tables.html

**Comment by sungwy** [comment]
Made a small tweak to the Issue title, as there is also ongoing work to raise the minimum required version to 17.0.0

**Comment by sungwy** [comment]
Resolved through #1090
