### ISSUE TITLE
`project_table` is deprecated, remove references

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#1119]
### Feature Request / Improvement

`project_table` is still used in the codebase, leading to deprecation warning 

https://github.com/apache/iceberg-python/blob/e4c1748fee220076f04e35ab2f182dd51ca20705/pyiceberg/io/pyarrow.py#L1493-L1498

Remove all references 
https://github.com/search?q=repo%3Aapache%2Ficeberg-python%20project_table&type=code

and use `ArrowScan.to_table` instead

**Comment by souravsingh** [comment]
Hello, I am interested in working on this.

**Comment by kevinjqliu** [comment]
sounds good, assigned to you

**Comment by JE-Chen** [comment]
I can’t replace all project_table using ArrowScan.to_table because ArrowScan.to_table is not a @staticmethod (need instance).

**Comment by kevinjqliu** [comment]
You can create an `ArrowScan` instance like so 
https://github.com/apache/iceberg-python/blob/0dc54080aa287dc8e920da128d7f4b335965f1df/pyiceberg/table/__init__.py#L1398-L1403

The args should be the same as `project_table`

**Comment by kevinjqliu** [comment]
Closed by #1180
