### ISSUE TITLE
Remove python 3.8 support

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#1121]
### Feature Request / Improvement

Python version 3.8 is EOL on October 2024
https://devguide.python.org/versions/

We should remove support for it soon 
See comment https://github.com/apache/iceberg-python/pull/1068#discussion_r1719872522

**Comment by sungwy** [comment]
+1. Shall we start a VOTE thread to vote on deprecating the support for it in the Mailing list?

**Comment by kevinjqliu** [comment]
I'll draft it up :) thanks

**Comment by sungwy** [comment]
I started the voting thread @kevinjqliu  🙂 

https://lists.apache.org/thread/d9r91hgq4wr30c2qm5y2zbkqb1nhjngh

**Comment by kevinjqliu** [comment]
@sungwy thanks! for following up, this fell off my radar

**Comment by kevinjqliu** [comment]
This was voted on via the devlist and passed
https://lists.apache.org/thread/50jjtdyfovwqbw8mp5m6rfgmmbxv7qcr
