### ISSUE TITLE
New PR label [ready for review]

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#1123]
### Feature Request / Improvement

To streamline the PR review process, I propose adding a new label like "ready for review" to signal that the PR is waiting for reviewers.

**Comment by sungwy** [comment]
As a counter argument, what's the difference between using this label, versus opening a PR in Draft mode?

**Comment by kevinjqliu** [comment]
Thats a good point. Ultimately I just want a filtered view of PRs that are waiting for review. 

I think there's already something available.

![Screenshot 2024-09-05 at 3 14 46 PM](https://github.com/user-attachments/assets/1e2a1260-eba5-4ebe-a9fb-b959902ae1ce)
