### ISSUE TITLE
Remove deprecated `datetime` functions

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#1133]
### Feature Request / Improvement

To support python 3.12 in #1068, we had to ignore warnings for deprecated `datetime` functions. 

Let's remove these deprecated functions from the codebase and also remove the warning filters.

https://github.com/apache/iceberg-python/blob/f2f428ec4d3c7d66b104ccaa235fc73fd0910bf3/pyproject.toml#L618-L619

**Comment by hussein-awala** [comment]
I can work on this issue
