### ISSUE TITLE
Minimum required pyarrow version

### ISSUE THREAD

**Issue by gli-chris-hao** [apache/iceberg-python#1174]
### Apache Iceberg version

0.7.1 (latest release)

### Please describe the bug 🐞

1. pyiceberg calls pyarrow `concat_tables` with `promote_options` here: https://github.com/apache/iceberg-python/blob/pyiceberg-0.7.1/pyiceberg/io/pyarrow.py#L1353

2. `promote_options` is only available in and after pyarrow 14.0.0 (added in this PR: https://github.com/apache/arrow/pull/36846)

3. however pyarrow version is pinned to ">=9.0.0,<18.0.0" in https://github.com/apache/iceberg-python/blob/pyiceberg-0.7.1/pyproject.toml#L61, I think it should be updated to ">=14.0.0,<18.0.0"

**Comment by kevinjqliu** [comment]
Thanks for reporting this. That makes sense to me. Is this something you would like to help contribute?

**Comment by sungwy** [comment]
Hi @gli-chris-hao thank you for reporting this issue! @ndrluis has already made a contribution to [fix this in main](https://github.com/apache/iceberg-python/pull/1090)
