### ISSUE TITLE
NumPy Hardpin 1.26 issue

### ISSUE THREAD

**Issue by anuraggautam14** [apache/iceberg-python#1198]
### Apache Iceberg version

0.7.1 (latest release)

### Please describe the bug 🐞

issue : 
In the latest version (0.7.1) , we notice that NumPy is hard-pinned at 1.26 (pyproject.toml link below) 
https://github.com/apache/iceberg-python/blob/main/pyproject.toml#L82-L85 

This is causing dependency issue in our environment where our other libraries need NumPy > 2

Expected Behaviour:

We expect NumPy to be flex pin to >= 1.26.4 < 3

**Comment by sungwy** [comment]
Hi @anuraggautam14 thanks for raising this issue.

This was actually intentionally imposed to solve an issue with pandas and numpy version compatibility. I'll take another pass at this to see if we can be more graceful about our version dependency here

**Comment by Fokko** [comment]
I think we can remove the numpy dependency completely once we get https://github.com/apache/iceberg-python/issues/1259 fixed. This will give flexibility to the user on which version to use
