### ISSUE TITLE
Block writing to sorted tables

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#1247]
### Apache Iceberg version

None

### Please describe the bug 🐞

Verify that we disallow writing an unsorted data frame to a table with sort order.

**Comment by sungwy** [comment]
Hi @kevinjqliu thanks for raising this. From the [docs](https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table-write-ordered-by) I'm understanding that sort order is purely suggestive, and it is up to the engines to decide if they will attempt to use the sort-order on write. It says:

"Iceberg tables can be configured with a sort order that is **used to automatically sort data that is written to the table in some engines**. For example, MERGE INTO in Spark will use the table ordering."

Would blocking the writes be the correct solution here, or should we just emit a warning log that PyIceberg doesn't respect sort orders?

**Comment by kevinjqliu** [comment]
> From the [docs](https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table-write-ordered-by) I'm understanding that sort order is purely suggestive, and it is up to the engines to decide if they will attempt to use the sort-order on write.

I don't think sort order is suggestive. My understanding is I can declare a sort order that is maintained for the table, its a contract like partition or schema.
Looking at https://iceberg.apache.org/spec/#sorting, 
"""
Users can sort their data within partitions by columns to gain performance. The information on how the data is sorted can be declared per data or delete file, by a sort order.
"""

The "default sort order id" might be optional.
"""
 A table could also be configured with a default sort order id, indicating how the new data should be sorted by default. Writers should use this default sort order to sort the data on write, but are not required to if the default order is prohibitively expensive, as it would be for streaming writes.
"""

In a scenario where I've declared a sort order for the table, and then write a dataframe that is not sorted according to the sort order, pyiceberg will still write the data as it is laid out in the dataframe. I think this deviates from the expected behavior. 

Heres an example,
```
import pyarrow as pa

from pyiceberg.table.sorting import SortDirection, SortField, SortOrder
from pyiceberg.table.update import AddSortOrderUpdate
from pyiceberg.transforms import IdentityTransform
from pyiceberg.catalog.sql import SqlCatalog


# Example data
int_data = [1, 2, 3, 4, 5]
string_data = ["a", "b", "c", "d", "e"]

# Create a PyArrow Table
table = pa.table({"int_field": pa.array(int_data), "string_field": pa.array(string_data)})

# Display the table
print(table.to_pandas())
print()

warehouse_path = "/tmp/warehouse"
catalog = SqlCatalog(
    "default",
    **{
        "uri": f"sqlite:///{warehouse_path}/pyiceberg_catalog.db",
        "warehouse": f"file://{warehouse_path}",
    },
)

identifier = "test.write_with_sort_order"
catalog.create_namespace_if_not_exists("test")
try:
    catalog.drop_table(identifier)
except:
    pass

staged_table = catalog._create_staged_table(identifier, schema=table.schema)

sort_order = SortOrder(*[SortField(source_id=1, transform=IdentityTransform(), direction=SortDirection.DESC)])
tbl = catalog.create_table(identifier, schema=staged_table.schema(), sort_order=sort_order)
print(tbl)
tbl.overwrite(table)
print(tbl.scan().to_pandas())
```

Output:
```
➜  iceberg-python git:(kevinjqliu/deprecate-0.8.0) ✗ poetry run python write_sort_order.py
   int_field string_field
0          1            a
1          2            b
2          3            c
3          4            d
4          5            e

write_with_sort_order(
  1: int_field: optional long,
  2: string_field: optional string
),
partition by: [],
sort order: [1 DESC NULLS LAST],
snapshot: null
/Users/kevinliu/repos/iceberg-python/pyiceberg/table/__init__.py:558: UserWarning: Delete operation did not match any records
  warnings.warn("Delete operation did not match any records")
/Users/kevinliu/repos/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.8.0, will be removed in 0.9.0. Table.identifier property is deprecated. Please use Table.name() function instead.
  _deprecation_warning(message)
/Users/kevinliu/repos/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.8.0, will be removed in 0.9.0. Support for parsing catalog level identifier in Catalog identifiers is deprecated. Please refer to the table using only its namespace and its table name.
  _deprecation_warning(message)
/Users/kevinliu/repos/iceberg-python/pyiceberg/utils/deprecated.py:51: DeprecationWarning: Deprecated in 0.8.0, will be removed in 0.9.0. Table.identifier property is deprecated. Please use Table.name() function instead.
  _deprecation_warning(message)
   int_field string_field
0          1            a
1          2            b
2          3            c
3          4            d
4          5            e
```

In the example, I declared a `DESC` order order while all the data in the dataframe is in ASC order. Writing is allowed and the result is in the order of the dataframe, not the order of the table

**Comment by kevinjqliu** [comment]
This might be a correctness issue. 
Maybe we can disable writing to a table with sort order for now, similar to what we do with equality deletes
https://github.com/apache/iceberg-python/blob/73ec7d92463037cbee87cc38a22db0421d668466/pyiceberg/table/__init__.py#L1452-L1453

**Comment by kevinjqliu** [comment]
According to #271, "We fail when we see a sort order".

**Comment by Fokko** [comment]
I don't think we should block the writes as that's pretty aggressive. What we do today when a table has a sort order, we write the data, but set the sort-order to none:

https://github.com/apache/iceberg-python/blob/0cebec48833f75eeca02b1a965112615b1cbc1c8/pyiceberg/io/pyarrow.py#L2461-L2464

This is similar to when you have an existing table and add a sort order. The existing data is unsorted. I don't think the behavior that we have today leads to correctness issues. The main thing is that when you do joins, having a pre-sorted file on the join-key could speed up the join substantially (and also compaction as mentioned earlier).

**Comment by kevinjqliu** [comment]
Thanks for the explanation! It looks like Sung was right and the table's sort order is not a constraint that must be enforced across the entire table and in all data files.
from the docs, https://iceberg.apache.org/spec/#sorting
```
Writers should use this default sort order to sort the data on write, but are not required to if the default order is prohibitively expensive, as it would be for streaming writes.
```

Closing this since we're already tracking support for writing a table with sort-order in #271
