### ISSUE TITLE
Change the glue catalog doc ( `list_tables` method only return Iceberg Tables )

### ISSUE THREAD

**Issue by omkenge** [apache/iceberg-python#1291]
### Feature Request / Improvement
In Glue Catalog
<img width="425" alt="image" src="https://github.com/user-attachments/assets/e120891f-0139-4422-952f-85530adb8447">

**Comment by kevinjqliu** [comment]
Thanks! I believe the docs are auto generated based on the comments in the function. 
https://py.iceberg.apache.org/reference/pyiceberg/catalog/glue/#pyiceberg.catalog.glue.GlueCatalog.list_namespaces

**Comment by omkenge** [comment]
IG.. It is present in docs only not in code base
