### ISSUE TITLE
Adaptive retry for Glue Catalog calls to fix Glue throttling

### ISSUE THREAD

**Issue by mark-major** [apache/iceberg-python#1294]
### Feature Request / Improvement

I have experienced throttling exceptions when multiple nodes are reading and writing an Iceberg table with a Glue catalog. I have wrapped my library calls in a retry wrapper, but this functionality should be implemented in the library instead.

I would add an option to the Glue catalog constructor to define the maximum number of retries and set the boto retry policy to standard instead of the default legacy. Standard is adding jitter to the retry interval which would ensure independent processes won't block each other ([Thundering herd problem](https://en.m.wikipedia.org/wiki/Thundering_herd_problem))

**Comment by Fokko** [comment]
Hey @mark-major thanks for jumping in here. I see that we only added retries to the REST catalog so far. Having this for the Glue catalog would be a great addition 👍

**Comment by mark-major** [comment]
I'm happy to work on this if I have some time.

**Comment by Fokko** [comment]
That would be great, happy to review! 🙌

**Comment by kevinjqliu** [comment]
we use boto3 to create the [glue client](https://github.com/apache/iceberg-python/blob/36e4de6cca1cc99adaf9579a92cb3a5aec6b9434/pyiceberg/catalog/glue.py#L299-L309)

looks like it has some built-in retry mechanism 
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#configuring-a-retry-mode

**Comment by mark-major** [comment]
@kevinjqliu Yes, we'll need the standard retry mode and the ability to configure the max attempts.

**Comment by mark-major** [comment]
PR #1307 is opened
