### ISSUE TITLE
to_pandas() API which converts iceberg table scan to a pd.DataFrame will lost datetime data type and row order 

### ISSUE THREAD

**Issue by zeddit** [apache/iceberg-python#132]
### Apache Iceberg version

0.5.0 (latest release)

### Please describe the bug 🐞

the code snippets look like below:
```
table = catalog.load_table("default.sample_table")
scan = table.scan()
# for pyarrow
patable = scan.to_arrow()
# result shows
## pyarrow.Table
## date: date32[day]
## time: time64[us]

# for pandas dataframe
df = scan.to_pandas()
df.info()
## date: object
## time: object
```

and when creating table with `sort_order`, pyiceberg won't read them out while keeping the order as stated in table schema. 
e.g. we sort the table with `sorted_by = ARRAY['date','time']`, however, the result df will have rows with early time behind the later one.

**Comment by Fokko** [comment]
@zeddit Thanks for raising this. I think the `sorted_by` is a local sort. Could you try a global sort by explicitly sorting on the two columns? The manifests in Iceberg are read sequentially, and should also return the tables in a sequential order.

**Comment by zeddit** [comment]
I will check the concept of `local sort` and `global sort`, there are many documents, thanks.

**Comment by rdblue** [comment]
The sort order for a table is a suggested write order. It is not guaranteed at read time. To get a sort order in your dataframe, you'll need to sort it.

**Comment by zeddit** [comment]
@rdblue thanks for your reply. 
I wanna know if this feature is challenge by design, why we don't guarantee it on read.

I think sorting or reordering in python is quite slow, so it will benefit a lot if we could just get out the data as the way it stored. that is to say, we move the heavy workload to the time when writing data, and just compose the data according to their offset.

In my opinion, if we need user to sort large dataset in python, it will make a lot use cases unusable. python is slow.

**Comment by zeddit** [comment]
@rdblue on the other hand, I wanna know if pyiceberg read data in a consistent way.

that is to say, if the data read out has the same order between runs.
e.g. I load the same table two times at 9:00 am and 10:00 pm, and they return me different lookings.

so the applications which use pyiceberg should have a knowledge about the volatility of the underlying data.

**Comment by zeddit** [comment]
https://stackoverflow.com/questions/74638658/delta-lake-table-storage-sorting
here is an expected behavior for me when pulling data with `pyiceberg` to pyarrow or pandas, especially for pandas.

the rows in the same partition should be placed together while their order is not important, while a flag is provided to control the order of partitions.
if local sort is used for partitions, the row order within partition will be persevered. in another word, the order is the one when data is being written.

**Comment by zeddit** [comment]
@rdblue it's great to find `pyiceberg` load data in a **deterministic** way, as what Fokko said, the manifests are read sequentially.
thus we only need to control the way how data is written, we could control the order of the final dataframe.

I have made a comprehensive experiment about the order when using different table schema(e.g. partition & sorted) and how data is written. I will post my report later here.

**Comment by zeddit** [comment]
@Fokko  In conclusion, even though pyiceberg loads data in a deterministic way, which means the results is preserved between runs, the results is far from arranged, which means we cannot achieve a ordered results without changing the logic of pyiceberg on how to assemble the data blocks.

However, it gives out a way to achieve this feature.

The main problem is to deal with partitions, for which even we conduct a global sort, the final order in manifest list is still a random one. I will introduce what I found during my experiments below.

But first, let me argue the importance of this feature, that is why we need a deterministic and in-order results for sorted tables.
It's mainly about time series data analysis use case, e.g. quant finance, which is the one shown in the homepage of `pyiceberg`. In these use cases, the order of data, e.g. every stock order and trade has timestamps and always make up of a time series data array, and a lot of data science works are conducted upon them to search the trends and relativities in time domain.

**Comment by zeddit** [comment]
Here are my experiments and main findings.
### 1. checking for consistent ordering of pyiceberg
firstly, I create an emtry table with no partition and sorted_by properties, and try to find if pyiceberg will return a deterministic results, because if pyiceberg load data in random, there is no way to achieve the goal.

I create the table with hive catalog in trino 
```
CREATE TABLE test_table1(
    date date
)
WITH (
    format = 'PARQUET',
    location = 's3a://test/test_table1'
);
```
and insert some values into it with
```
INSERT INTO test_table1 VALUES (date '2021-01-04');
```
I have inserted a sequence of date one by one, e.g. '2021-01-01', '2021-01-04', '2021-01-03', '2021-01-07', '2021-01-02'. the seq is not sorted.
Every insertion will create a snapshot, and because we insert the row one by one, each row will be put in it's own data-file.

After making that table, we start to select/read the table, and observe the result.
In trino, when using `select * from test_table1`, there won't be a consistent result, every row could be in any position.
while in pyiceberg, the order of rows is fixed, and it is the reverse one as we insert the rows.
I run the load_table 100 times and compare the results of every run, they all returns the same order.

And when I try to insert some new rows into the table, it shows up in the front few lines in the results. e.g. we adding '2021-01-05', '2021-01-09', '2021-01-06', '2021-01-08' one by one
<img width="123" alt="截屏2023-11-09 11 37 58" src="https://github.com/apache/iceberg-python/assets/30164206/0f30573c-a2f8-4d66-b312-e225ef49f4c0">

I also checked the source code in pyiceberg/io/pyarrow.py. there is a consistent ordering for reading data-files, and within each data-file, the order is the one when writting.

Then I use `alter table test_table1 execute optimize;` to merge them into one data-file. 
After that, both trino client and pyiceberg will return a consistent result. it's because there is only one data-file, so the order in it is preserved.
However, if the table has no `sorted_by` properties, there is no order guarantee when compact the data-files.

**Comment by zeddit** [comment]
### 2. adding sorted_by properties, or the term of sort_order in iceberg
because we want a sorted iceberg table to store and return time series data.
so we create a sorted_by table in Trino with
```
CREATE TABLE test_table2(
    date date
)
WITH (
    format = 'PARQUET',
    location = 's3a://test/test_table2',
    sorted_by = ARRAY['date']
);
```
and we check the table properties in pyiceberg CLI to make sure sort_order properties is set
```
$ pyiceberg describe test_table2
Table format version  2
Metadata location     s3a://test/test_table2/metadata/00025-cd229550-87da-4b49-8013-28d862e8…
Table UUID            e9c38f74-f556-43b2-a9f9-6facdd884723
Last Updated          1699465355600
Partition spec        []
Sort order            [
                        1 ASC NULLS FIRST
                      ]
Current schema        Schema, id=0
                      └── 1: date: optional date
```
Then we insert the rows again to this new table. We still insert them one by one, with a same sequence like '2021-01-01', '2021-01-04', '2021-01-03', '2021-01-07', '2021-01-02', '2021-01-05', '2021-01-09', '2021-01-06', '2021-01-08'.

Then we start to get data out of the new table. 
In trino, when using select * from test_table1, there still is no consistent order, the result returned varies between runs.
In pyiceberg, it's good to see there is a fixed order, however, the order is not the Ascending order that we stated and want for the table. It's because we insert rows one by one, and they are in different data-files underlying.

When we compact the table into one data-file with Trino `alter table test_table2 execute optimize;`. 
The result both in trino and pyiceberg is fixed and ordered. that is because there is only one data-file and the result order is the one that how data is written into that data-file. 
When specifying `sorted_by` properties, a local sort will be performed to ensure that in each data-file, there will be in order.

Then we try to append the same amount of data into the sorted table with
```
insert into test_table2 select * from test_table1;
```
we got the result below:
<img width="123" alt="截屏2023-11-09 12 04 17" src="https://github.com/apache/iceberg-python/assets/30164206/b05a3e25-eacd-45a1-8d63-7442fb3fe12d">
It's not correct, what we expected is 
<img width="126" alt="截屏2023-11-09 12 04 43" src="https://github.com/apache/iceberg-python/assets/30164206/976d1022-4b1e-488c-8866-4f465db40176">
it's because the second insert store rows in another data-file, which is just concat with the one before.

when using `alter table test_table2 execute optimize;` to merge them, the result is as expected.

**Comment by zeddit** [comment]
### 3. how about partitioned tables
it is a common case for people to use partition to manage tables, and in iceberg partition will lead to a great performance gain by skipping a lot of some data-files.
we test the order behaviors with the following two tables.
```
CREATE TABLE test_table3(
    date date
)
WITH (
    format = 'PARQUET',
    format_version = 2,
    location = 's3a://test/test_table3',
    partitioning = ARRAY['month(date)'],
    sorted_by = ARRAY['date']
)
---
 CREATE TABLE test_table4 (
    date date,
    sym varchar
 )
 WITH (
    format = 'PARQUET',
    format_version = 2,
    location = 's3a://test/test_table4',
    partitioning = ARRAY['sym'],
    sorted_by = ARRAY['sym','date']
 )
```
We also insert some values and get the results to observe their orders.
It's a bad news that the order between partitions will never be under controlled by any means of controlling the writing method. e.g. even when we conduct a global sort, the month order in the final result is still a random one, which make time series analysis disappointed.

**Comment by zeddit** [comment]
### 4. limitations about the experiments
I have not tested the case for

- 1. when data is large enough and get split with a partition, i.e. multiple data-files and they contain part-of the whole data.
- 2. what will happen when a row deletion occurs, if the order would be messed up.
- 2. what will happen when scheme evolve occurs.

**Comment by zeddit** [comment]
I have a first step idea that we could add a parse module which inspect the manifests and determine an order for how to concat pa.tables to assemble the final output. I don't know if it could be realizable.

I will dig into the structure of manifest and return with more feedbacks.

**Comment by Fokko** [comment]
> In my opinion, if we need user to sort large dataset in python, it will make a lot use cases unusable, especially for time series cases. python is slow, not the way like MPP or spark situation.

I agree there, but the API is often just in Python. For example, we use PyArrow, which pushes it down into the C++ layer.

> I wanna know if pyiceberg read data in a consistent way.

Yes, we do some ordering. This is important when we fetch the top n rows, we always want to return the same rows, and not the ones that came back the quickest.

> if local sort is used for partitions, the row order within partition will be persevered. in another word, the order is the one when data is being written.


Yes this is true, and I think you can achieve this today. Especially when the data is small (which it is in your case IIRC from Slack), then you could just write a single file for the partition.

> Every insertion will create a snapshot, and because we insert the row individually, each row will be put in it's own data-file.

Every insertion being a new snapshot is okay, but I think it will also create a new manifest per commit. Trino uses [fast-append](https://iceberg.apache.org/spec/#snapshots) which means that for each append operation a new manifest is created, instead of rewriting the existing metadata. We [keep the order of sequences](https://github.com/apache/iceberg-python/blob/main/pyiceberg/table/__init__.py#L871-L875) since the Python list will maintain order.

> Then we try to append the same amount of data into the sorted table with

If you would add a `ORDER BY 1` you'll introduce a global sort which should probably fix without needing to optimize the table.

> It's a bad news that the order between partitions will never be under controlled by any means of controlling the writing method. e.g. even when we conduct a global sort, the month order in the final result is still a random one, which make time series analysis disappointed.

I think you can also fix this by adding an `ORDER BY`.

> when data is large enough and get split within a partition, i.e. multiple data-files and they contain part-of the whole data.

If your data is relative small, then having a single file is best. Also, you could tune the row group sizes to get decent parallism (PyArrow will do this for you).

> what will happen when a row deletion occurs, if the order would be messed up.

The order should be maintained. 

> what will happen when scheme evolve occurs.

Should not influence the order since it is just schema projection.

> besides, it's quite strange that for rows newly inserted to show at the top of the final results, it will add challenge to integrated with the data ingestion subsystem in my opinion. any advices on it.

I think this depends mostly on Trino, on how the data is written. As mentioned earlier, the fast-append might mess things up because you're relying on how Trino produces the manifest.

**Comment by zeddit** [comment]
@Fokko great thanks for your help.
I do some more experiments according to your advices.

I wonder if I correctly understand the `global sort` right. I think it's a way to arrange the list of manifest that pyiceberg will follow when using engine like trino to write data.

I first create a sorted table with
```
CREATE TABLE iceberg.sort_order_exp.csdate100 (
    date date
)
WITH (
    format = 'PARQUET',
    format_version = 2,
    location = 's3a://test/csdate100',
    sorted_by = ARRAY['date']
);
```
Then I try to insert rows into it one by one with 
```
INSERT INTO iceberg.sort_order_exp.csdate100 VALUES (date '2021-01-01') ORDER BY 1;
INSERT INTO iceberg.sort_order_exp.csdate100 VALUES (date '2021-01-04') ORDER BY 1;
INSERT INTO iceberg.sort_order_exp.csdate100 VALUES (date '2021-01-03') ORDER BY 1;
INSERT INTO iceberg.sort_order_exp.csdate100 VALUES (date '2021-01-07') ORDER BY 1;
INSERT INTO iceberg.sort_order_exp.csdate100 VALUES (date '2021-01-02') ORDER BY 1;
INSERT INTO iceberg.sort_order_exp.csdate100 VALUES (date '2021-01-05') ORDER BY 1;
INSERT INTO iceberg.sort_order_exp.csdate100 VALUES (date '2021-01-09') ORDER BY 1;
INSERT INTO iceberg.sort_order_exp.csdate100 VALUES (date '2021-01-06') ORDER BY 1;
INSERT INTO iceberg.sort_order_exp.csdate100 VALUES (date '2021-01-08') ORDER BY 1;
````
which would trigger a global sort who place the manifest in list in a right order.

However, the results show that the order of manifest won't be right and the dataframe read out by pyiceberg is the one how rows are inserted one by one. i.e.
<img width="468" alt="截屏2023-11-09 21 14 35" src="https://github.com/apache/iceberg-python/assets/30164206/98c64493-2197-4169-879a-60a2b5f2a494">

or it's an issue related with Trino, other engine like spark has no such problems?

great thanks.

**Comment by zeddit** [comment]
@Fokko  it seems that trino always using fast-append operation is not a good choice.
is there any documentation introducing how each engine modify manifests, and could you give me an advice about which one supports iceberg best in your opinion. great thanks.

**Comment by Fokko** [comment]
@zeddit there is always a trade-off. Fast-append are quicker and are less likely to suffer from conflicts. Please check [this](https://iceberg.apache.org/spec/#snapshots) link, and go through the bullet points below the table. I personally think that potentially avoiding conflicts is more valuable than maintaining order. Not because I think maintaining order isn't valuable, but it is just very hard to do in a distributed environment (therefore sort-order isn't a hard guarantee, but it depends on the query-engine implementation).

**Comment by zeddit** [comment]
@Fokko great thanks for your reply.

I have carefully read the bullets and I am still not clear if it is realizable for `pyiceberg` to pull out data in a in-order way, i.e. 1) rows in the same partition are placed adjacent and in-order, 2) partitions are placed in order, e.g. if we partition with months, then months should be placed in a growing way.

and what effort we need to do to achieve that, i.e. 1) conduct global sort (with the right engine, trino is not the right one), 2) change to another engine like spark than trino who implement global sort that is more consistent with pyiceberg in semantic, 3) modify the pyiceberg source code to assemble data-files in the right order, 4) control the flow how we write data, or 5) there is no way to achieve that.

As my test, with trino we could not achieve that by using global sort. I think it's an interoperability issue for trino and pyiceberg. I still has the opinion that pyiceberg has a different view than other distributed query engine because it's architecture and python has no capacity to reorder dataset of more than 100GB well.

p.s. sorry for me. I didn't get the point about what's the meanings of `conflict` well,  is that when multiple writer is writing the same partition simultaneously and iceberg needs to support transaction which requires to keep the order between each operation. is there any documentation for me to learn why this could be a problem to keep the order.
I am sorry to have too many questions, great thanks for you.
