### ISSUE TITLE
Remove upper Python version constraint to enable early testing

### ISSUE THREAD

**Issue by bigluck** [apache/iceberg-python#1348]
### Feature Request / Improvement

Currently, `pyiceberg 0.8.0` enforces strict Python version constraints (`python = "^3.9, <3.13, !=3.9.7"`).

While I understand the reasoning behind this - Python 3.13 hasn't been officially tested and supported yet - this constraint creates some practical limitations.

The main issue is that it prevents early adopters and developers from testing or using pyiceberg with newer Python versions, as package managers like `poetry` and `pip` will strictly enforce these version constraints and block the installation.

Given that:
1. Major releases of pyiceberg can take up to 5 months
2. Minor releases can take up to 1.5 months
3. Early testing with newer Python versions can help identify compatibility issues sooner (see https://github.com/apache/iceberg-python/pull/1256#issuecomment-2442124313)

I suggest removing the `<3.13` constraint from the Python version specification. This would allow developers to:
- Test pyiceberg with pre-release Python versions
- Identify potential compatibility issues earlier
- Continue using pyiceberg in environments with newer Python versions (at their risk)
- Provide feedback about compatibility issues

**Comment by kevinjqliu** [comment]
SGTM! We don't necessarily have to enforce the upper bound

**Comment by Fokko** [comment]
> We don't necessarily have to enforce the upper bound

I agree!

@bigluck are you interested in creating a PR?

**Comment by bigluck** [comment]
Done :) :
- https://github.com/apache/iceberg-python/pull/1355

@Fokko / @kevinjqliu once merged can we include this hotfix to the next minor release?

**Comment by kevinjqliu** [comment]
yes fokko just started a thread on devlist for 0.8.1
https://lists.apache.org/thread/j4l5xk92j6z3pb31wyqtxk7fbf1621kv
