### ISSUE TITLE
Implement `namespace_exists` function on the REST Catalog

### ISSUE THREAD

**Issue by sungwy** [apache/iceberg-python#1430]
### Feature Request / Improvement

Implement `namespace_exists` function that returns a boolean value using the [HEAD request endpoint](https://github.com/apache/iceberg/blob/540d6a6251e31b232fe6ed2413680621454d107a/open-api/rest-catalog-open-api.yaml#L372-L402) on the REST Catalog

The implementation should be similar to the already supported `table_exists` function

**Comment by AhmedNader42** [comment]
Would love to implement this functionality if no one is assigned

**Comment by kevinjqliu** [comment]
@AhmedNader42 assigned to you!

**Comment by AhmedNader42** [comment]
Submitted #1434

**Comment by kevinjqliu** [comment]
Closed by #1434
