### ISSUE TITLE
Clarify documentation related to X-Iceberg-Access-Delegation header

### ISSUE THREAD

**Issue by EternalDeiwos** [apache/iceberg-python#1441]
### Feature Request / Improvement

Following #1028, it [took a bit of digging](https://apache-iceberg.slack.com/archives/C029EE6HQ5D/p1734445388543979) to figure out how to connect pyiceberg to Nessie using the S3V4RestSigner.

Eventually I was helped in both communities to find that pyiceberg defaults to setting `X-Iceberg-Access-Delegation: vended-credentials`, which means that Nessie will not supply the `s3.signer` information in the resulting io properties.

This header is not documented anywhere in the pyiceberg docs; although I was very glad to see there was already the ability to override headers in the client config. At the very least, there should be some documentation for this, and ideally some way to remove the default header, i.e. allowing the catalog to decide how it wants to respond.

**Comment by Fokko** [comment]
Thanks for raising this @EternalDeiwos Are you interested in providing a patch to fix the documentation?

**Comment by Fokko** [comment]
And I agree, according to the spec, it is optional: https://github.com/apache/iceberg/blob/b428fbc59bd1579f4dc918a5cd48fce667d81ce1/open-api/rest-catalog-open-api.yaml#L1831-L1845

cc @nastra

**Comment by EternalDeiwos** [comment]
I am not super familiar with the spec but it looks like that is the only header? If that's the case I'd be happy to.

**Comment by kevinjqliu** [comment]
> but it looks like that is the only header?
did a quick search in the spec for `header` and it does look like the only one

**Comment by kevinjqliu** [comment]
The ability to override access delegation header was implemented in #1033
