### ISSUE TITLE
Token required even when request-signing-enabled

### ISSUE THREAD

**Issue by EternalDeiwos** [apache/iceberg-python#1442]
### Apache Iceberg version

0.8.1 (latest release)

### Please describe the bug 🐞

When attempting to read a table using `s3.signer: S3V4RestSigner`, pyiceberg throws an error if `token` and `s3.session-token` are not set. This is currently mitigated by putting placeholder values in the catalog configuration:

```python
catalog = load_catalog(
    'lab',
    **{
        'uri': 'https://datalake.internal.redacted:19121/iceberg',
        'warehouse': 'lab',
        'header.X-Iceberg-Access-Delegation': 'remote-signing',
        'token': 'placeholder',
        's3.session-token': 'placeholder',
    }
)
```

<details>
<summary>table.io.properties</summary>

```
{
    "client.region": "eu-central-1",
    "created-at": "2024-12-17T09:38:26.258561460Z",
    "gc.enabled": "false",
    "header.X-Iceberg-Access-Delegation": "remote-signing",
    "io-impl": "org.apache.iceberg.aws.s3.S3FileIO",
    "nessie.catalog-base-uri": "https://datalake.internal.redacted:19121/catalog/v1/",
    "nessie.catalog.content-id": "dc71c47d-090c-42ac-bd80-33e63a414a19",
    "nessie.commit.id": "9a2572b36c83be67eaec3a78e57bbc2f7bfe81e996979c13b201fd1e18199ba5",
    "nessie.commit.ref": "main",
    "nessie.core-base-uri": "https://datalake.internal.redacted:19121/api/",
    "nessie.default-branch.name": "main",
    "nessie.iceberg-base-uri": "https://datalake.internal.redacted:19121/iceberg/",
    "nessie.is-nessie-catalog": "true",
    "nessie.prefix-pattern": "{ref}|{warehouse}",
    "owner": "spark",
    "prefix": "main%7Clab",
    "py-io-impl": "pyiceberg.io.fsspec.FsspecFileIO",
    "rest-metrics-reporting-enabled": "false",
    "rest-page-size": "200",
    "s3.endpoint": "https://s3.eu-central-1.amazonaws.com/",
    "s3.remote-signing-enabled": "true",
    "s3.signer": "S3V4RestSigner",
    "s3.signer.endpoint": "v1/main%7Clab/s3sign/H4sIAAAAAAAA...U9NuAQAA",
    "s3.signer.uri": "https://datalake.internal.redacted:19121/iceberg/",
    "s3.use-arn-region-enabled": "true",
    "uri": "https://datalake.internal.redacted:19121/iceberg/",
    "warehouse": "lab"
}
```

</details>

### Willingness to contribute

- [ ] I can contribute a fix for this bug independently
- [ ] I would be willing to contribute a fix for this bug with guidance from the Iceberg community
- [X] I cannot contribute a fix for this bug at this time

**Comment by kevinjqliu** [comment]
From the code, `S3V4RestSigner` requires `TOKEN` in `properties`
https://github.com/apache/iceberg-python/blob/392c9ce0f05c43f92b649b4d1d79d34a2119cd70/pyiceberg/io/fsspec.py#L96-L99

This was first added [here](https://github.com/apache/iceberg-python/commit/dad323ca08ab19379668ba4ae5135adf77d5eaf4#diff-24c3aa912b523fdb2afba6a0ea2dfe69fdcd05d9268e1e13ac1023ac26b54cccR39-R40)

Im not sure what the context is, lets wait for @Fokko to chime in

**Comment by EternalDeiwos** [comment]
When I was trying this out, it gave the same error unless both `s3.session-token` and `token` were present.

In hindsight this could also have been due to a dirty environment.

**Comment by kevinjqliu** [comment]
`"s3.session-token"` is represented by `S3_SESSION_TOKEN` which is used by the S3 FileSystem
https://github.com/apache/iceberg-python/blob/392c9ce0f05c43f92b649b4d1d79d34a2119cd70/pyiceberg/io/fsspec.py#L140-L163

**Comment by Fokko** [comment]
@EternalDeiwos Thanks for raising this, let's debug this together. What kind of catalog are you using? With remote signing, you need a token to authenticate yourself and get the signature from the catalog. So I would expect the token to be there, maybe you can share the redacted properties that you get back from the `/config` endpoint.

**Comment by Fokko** [comment]
It looks like the authentication to the catalog is working fine, but when it triest to perform the scan. That's the first time it will go to the object store to fetch the manifest-list. Based on the configuration, PyIceberg will reach out to the catalog to sign the request to the object store, but there is not token. For me it feels like to login without a password, but I noticed that it is allowed on the Java side: https://github.com/apache/iceberg/blob/91a1505d09cebcd1d088ac53cd42732c343883de/aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java#L205

Let me create a PR to get this fixed 👍
