### ISSUE TITLE
Uploading Data to Iceberg

### ISSUE THREAD

**Issue by Atiqul-Islam** [apache/iceberg-python#181]
### Question

We are using Iceberg with a minio storage and a jdbc (postgresql) catalog. 
We are not using Apache Spark. We are using trino for retrieving data from iceberg. 

I am trying to write a python function that would append a dataframe to an existing icerberg table. 

I looked over the documentation for the pyiceberg API but I counldn't spot a function for uploading data or for syncing the iceberg catalog once data is moved into the minio storage associated to the iceberg table.

Any suggestions on the process of  uploading batch data to iceberg would be really appreciated.

**Comment by Fokko** [comment]
Thanks for reaching out @Atiqul-Islam, this functionality is in-flight in https://github.com/apache/iceberg-python/pull/41

**Comment by dbuades** [comment]
I agree that this functionality will be very useful, thank you @Fokko for working on this !

Do you happen to have any ETA for that PR?

**Comment by Fokko** [comment]
@dbuades We're aiming for this year :)

**Comment by dbuades** [comment]
> @dbuades We're aiming for this year :)

That's great to hear, thank you!
