### ISSUE TITLE
Create namespace through the CLI

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#185]
### Feature Request / Improvement

It would be nice to be able to create a namespace through the CLI.

**Comment by detunjiSamuel** [comment]
hey, I would love to take up this task. Please could you assign it to me?

**Comment by Fokko** [comment]
Done! Looking forward to it! 👍

**Comment by hendrikmakait** [comment]
@detunjiSamuel: It looks like there's no PR yet. Are you actively working on this? If not, I'd love to take this over.
