### ISSUE TITLE
When will the 0.6.0 version be released?

### ISSUE THREAD

**Issue by 1taoze** [apache/iceberg-python#192]
### Feature Request / Improvement

I am looking forward to the writing feature that will be released in version 0.6.0, and I would like to know approximately when it will be released.

**Comment by Fokko** [comment]
@1taoze The goal is this year, and I'm quite confident that it is realistic.

**Comment by Michal-Bobrowsky** [comment]
still realistic?

**Comment by Fokko** [comment]
We're almost ready to release, I would like to include one more bugfix that comes with Arrow 15

**Comment by asheeshgarg** [comment]
@Fokko current write support doesn't support nested structure writes?

**Comment by Fokko** [comment]
I've sent out a `[DISCUSS]` thread: https://lists.apache.org/thread/6hsqmdlv6q3f56syopfjfoprf9por6rx

**Comment by Fokko** [comment]
It has been released: https://pypi.org/project/pyiceberg/
