### ISSUE TITLE
Add partition evolution

### ISSUE THREAD

**Issue by nicor88** [apache/iceberg-python#193]
## Context
One of the advantage of Iceberg is that the original "partition" design can be changed over time. This is often the case, as a table is originally implemented for a specific query access pattern, and that can change over time.

## Requirements
I would like to use pyiceberg to "evolve" partitions, specifically changing the partition specs.
e.g.
```
new_partition_spec = PartitionSpec(
    PartitionField(source_id=1, field_id=1000, transform=DayTransform(), name="event_date"),
   PartitionField(source_id=2, field_id=1001, name="marketing_channel")
)

with table.update_partitions() as table_update:
   table_update. update_partition_specs(new_partition_spec)
```
or something similar.

## Reference
https://iceberg.apache.org/docs/latest/evolution/#partition-evolution

**Comment by amogh-jahagirdar** [comment]
If anyone's not already working on this @Fokko I'd love to try and take a stab at this!

**Comment by syun64** [comment]
@Fokko Should we move this to 0.7.0 release Milestone?

**Comment by amogh-jahagirdar** [comment]
@syun64 Yes, I think 0.7.0 would be the right milestone to move this to. I wouldn't want to hold up the 0.6 release on partition evolution capabilities. Wonder what @Fokko thinks though
