### ISSUE TITLE
Support 'schema.name-mapping.default' Column Projection property

### ISSUE THREAD

**Issue by syun64** [apache/iceberg-python#202]
### Feature Request / Improvement

schema.name-mapping.default property is well supported in Spark Iceberg in order to enable column consistent reads for Iceberg tables that rely on migration procedures, where the field metadata of the underlying data files may not align with the current schema ids of the iceberg table.

We should enable support for this property on PyIceberg to make sure that read operations are not misaligning data onto the wrong columns.

[Add NameMapping to Spec Document](https://github.com/apache/iceberg/issues/3542)
[Column Projection](https://iceberg.apache.org/spec/#column-projection)

**Comment by Fokko** [comment]
@syun64 Thanks for raising this, is this something that you're interested in contributing?

**Comment by syun64** [comment]
@Fokko Absolutely 👍

**Comment by Fokko** [comment]
As discussed on Slack, I've taken the liberty to get in [all the name-mapping plumbing](https://github.com/apache/iceberg-python/pull/212) ((de)serializers, visitors etc). The thing left for this issue is to correctly wire up the table property, and pass in the name-mapping.
