### ISSUE TITLE
Set table properties through Hive

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#206]
### Feature Request / Improvement

Allow setting table properties through Hive

**Comment by zenfenan** [comment]
@Fokko Could you please share more context on this one? If I understand this correctly, this is about setting table properties through `HiveCatalog`. That seems to be already available (correct me if I am wrong).

Would be happy to pick it up otherwise :)

**Comment by kevinjqliu** [comment]
This is already done using [`session_catalog_hive` ](https://github.com/apache/iceberg-python/blob/678facc09b99394acf4c1c12b5a8a67bf2a20f5d/tests/conftest.py#L2202-L2213) in [`test_table_properties`](https://github.com/apache/iceberg-python/blob/678facc09b99394acf4c1c12b5a8a67bf2a20f5d/tests/integration/test_reads.py#L82-L109)
