### ISSUE TITLE
Ability to the write Metadata JSON

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#22]
### Feature Request / Improvement

Migrated from https://github.com/apache/iceberg/issues/7257

**Comment by HonahX** [comment]
Hi @Fokko. Is there an update on this issue? I am interested in taking this if it's still open.

In terms of implementation, I was thinking of something like this:
```python
def update_table_metadata(base_metadata: TableMetadata, updates: Tuple[TableUpdate, ...]) -> TableMetadata:
    builder = TableMetadataUpdateBuilder(base_metadata)
    for update in updates:
        builder.update_table_metadata(update)
    return builder.build()
```
Does this approach align with your expectations?
Thanks!

**Comment by Fokko** [comment]
@HonahX Yes, I think that is how it should be done (Except the builder pattern, that's very much Java style :). I think we can split the work into several work packages:

- Ability to write the JSON to the object store (that was the intent of this PR).
- Have logic to update the metadata dictionary as you pointed out above. I think we can do this per operation (update schema, update partition-spec, update sort-order, etc) to keep it small and we can get it in quickly. 
- Implement the commit method per catalog to update the properties (point to the latest metadata, and [set the previous metadata](https://github.com/apache/iceberg/blob/b0bf62a448617bd5f57ca72c2648452e6600fa20/core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java#L58)).

**Comment by vrd83** [comment]
Guys, is this a prerequisite for altering the [write-ordered-by ](https://iceberg.apache.org/docs/latest/spark-ddl/#alter-table--write-ordered-by) on a table?

**Comment by HonahX** [comment]
Hi @vrd83. It depends on which catalog you want to use to alter the table.

For the RestCatalog, this is not a prerequisite. To enable altering the write order, we can implement a `ReplaceSortOrder` ( `UpdateSortOrder`) in a similar manner to how we currently support UpdateSchema. You can see how` UpdateSchema` is implemented here for reference:
https://github.com/apache/iceberg-python/blob/03fa9f0b6a86fc13d855b24ce92e07b145faa500/pyiceberg/table/__init__.py#L1314-L1319
https://github.com/apache/iceberg-python/blob/03fa9f0b6a86fc13d855b24ce92e07b145faa500/pyiceberg/table/__init__.py#L264-L270

For other catalogs, such as Glue, DynamoDB, SQL, and Hive, this will be a prerequisite. We need the `ReplaceSortOrder` thing and the three bullet points listed by @Fokko above.

@Fokko, please correct me if I've missed anything about the RestCatalog part

**Comment by HonahX** [comment]
@Fokko Thanks for the explanation! 

> Ability to write the JSON to the object store (that was the intent of this PR).

 I think we already support this:https://github.com/apache/iceberg-python/blob/8e8d39dacde067773d6d840b9bf65070399957a9/pyiceberg/catalog/__init__.py#L571-L572
Could you please elaborate on this a bit? Are there additional features we are looking to implement beyond the `_write_metadata` method?

> Have logic to update the metadata dictionary as you pointed out above. I think we can do this per operation (update schema, update partition-spec, update sort-order, etc) to keep it small and we can get it in quickly.

I plan to start with `update_schema`, `set_snapshot_ref`, and `add_snapshot`, given that update_schema is already supported and the other two operations are pivotal for write support.

I will try to make a draft PR soon for further discussion.

**Comment by Fokko** [comment]
> @Fokko, please correct me if I've missed anything about the RestCatalog part

No I think that's about right.

> Could you please elaborate on this a bit? Are there additional features we are looking to implement?

Ah, I see. You're right there. I was thinking about the logic of generating a filename and doing the actual write.

> I plan to start with update_schema, set_snapshot_ref, and add_snapshot, given that update_schema is already supported and the other two operations are pivotal for write support.

That sounds like a great start to me 👍
