### ISSUE TITLE
Slowness when loading table from S3

### ISSUE THREAD

**Issue by itaise** [apache/iceberg-python#220]
### Apache Iceberg version

0.3.0

### Please describe the bug 🐞

Hi,
I am trying to read a table schema.  for our use case - we need only field names and types 
The operation of load_table is very slow, it takes about 30 seconds. 
I checked the metadata file on S3 and it is ~9MB, and the table has ~900 columns. 
The slowness happens when opening the metadata file from S3. 
is this a known issue? 
Is there a faster way to get the table schema? 

Thanks a lot! 
This is the code we use (we have hive metastore + S3 storage):

```
from pyiceberg.catalog import load_catalog
catalog = load_catalog("prod")
table = catalog.load_table("stores.checkout")
table
```

**Comment by itaise** [comment]
Hi, 
The PyIceberg version that we use is 0.5.1.. 
Sorry I wrote the wrong one when opening the ticket. 
BTW Our iceberg version is 1.3.0.
Any other way to make the reading of metadata faster? thanks!

**Comment by anechii** [comment]
@itaise currently facing the same issue, but on a larger scale (bigger table, bigger metadata).
Did you find a way to speed this up ?
Thanks.

**Comment by itaise** [comment]
Hi,
Actually i didnt. Will love to hear if there is a way. We would like to get
only table metadata in the fastest way possible (for user facing UIs)

בתאריך יום ו׳, 26 בינו׳ 2024, 12:51, מאת anechii ***@***.***
