### ISSUE TITLE
Remove deprecated import

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#221]
### Feature Request / Improvement

I noticed this warning in the logs today:

```
../../Library/Caches/pypoetry/virtualenvs/pyiceberg--PPis2RJ-py3.11/lib/python3.11/site-packages/pyspark/broadcast.py:38
  /Users/fokkodriesprong/Library/Caches/pypoetry/virtualenvs/pyiceberg--PPis2RJ-py3.11/lib/python3.11/site-packages/pyspark/broadcast.py:38: DeprecationWarning: typing.io is deprecated, import directly from typing instead. typing.io will be removed in Python 3.12.
    from typing.io import BinaryIO  # type: ignore[import]

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

**Comment by Rohit-Pujari** [comment]
Hi iam Rohit, I am a beginner to open source contribution I could try to solve the above issue

**Comment by Fokko** [comment]
@Rohit-Pujari feel free to raise a PR 👍

**Comment by Rohit-Pujari** [comment]
sorry for the inconvenience , when i open the broadcast.py file on my machine the issue is already solved there is no need to modify it

**Comment by Fokko** [comment]
This is actually in Spark, and you're right @Rohit-Pujari, I think we can close it. Thanks for checking
