### ISSUE TITLE
Remove MockAWSResponse and pyiceberg.io.fsspec.FsspecFileIO from testing

### ISSUE THREAD

**Issue by sebpretzer** [apache/iceberg-python#222]
### Feature Request / Improvement

Hi Team,

I was attempting to mess around with `PyIceberg` for my data pipelines. I was struggling implementing the same test framework due to dependency mismatch in regards to how the `MockAWSResponse` was implemented. After a few attempts at fixing the patch itself, I managed to circumvent the issue completely using a [moto server](http://docs.getmoto.org/en/latest/docs/server_mode.html#start-within-python).

I have implemented the change in a [fork of the repo](https://github.com/sebpretzer/iceberg-python/tree/moto_server_implementation), to show you how it works. This removes the need to patch `aiobotocore` and use `FsspecFileIO` ([relevant old convo](https://github.com/apache/iceberg/pull/6822#discussion_r1104878428)). I have made sure this passes tests (at least on my machine). 

Would it be ok for me to open a PR and carry these changes though? Thanks!

**Comment by Fokko** [comment]
Closing this one since the PR is in, thanks for working on this @sebpretzer 🙌
