### ISSUE TITLE
Schema IDs Re-Order?

### ISSUE THREAD

**Issue by sebpretzer** [apache/iceberg-python#229]
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

When publishing a schema via `create_table`, the `id`s sometimes re-order. I haven't looked into all cases, but I have noticed this specifically with glue, specifically for nested/complex types. This does not happen when using the `InMemoryCatalog`. I have started a branch with tests that re-create this issue here: https://github.com/sebpretzer/iceberg-python/tree/schema_id_reordering (if you do look at my code, please ignore the `schema_id=0` in `conftest.py` for now)

Is this in fact a bug, or is this intended behavior? 

`table_schema_nested` vs `table.schema()`:
```diff
{
  "type": "struct",
  "fields": [
    {
      "id": 1,
      "name": "foo",
      "type": "string",
      "required": false
    },
    {
      "id": 2,
      "name": "bar",
      "type": "int",
      "required": true
    },
    {
      "id": 3,
      "name": "baz",
      "type": "boolean",
      "required": false
    },
    {
      "id": 4,
      "name": "qux",
      "type": {
        "type": "list",
-        "element-id": 5,
+        "element-id": 8,
        "element": "string",
        "element-required": true
      },
      "required": true
    },
    {
-      "id": 6,
+      "id": 5,
      "name": "quux",
      "type": {
        "type": "map",
-        "key-id": 7,
+        "key-id": 9,
        "key": "string",
-        "value-id": 8,
+        "value-id": 10,
        "value": {
          "type": "map",
-          "key-id": 9,
+          "key-id": 11,
          "key": "string",
-          "value-id": 10,
+          "value-id": 12,
          "value": "int",
          "value-required": true
        },
        "value-required": true
      },
      "required": true
    },
    {
-      "id": 11,
+      "id": 6,
      "name": "location",
      "type": {
        "type": "list",
-        "element-id": 12,
+        "element-id": 13,
        "element": {
          "type": "struct",
          "fields": [
            {
-              "id": 13,
+              "id": 14,
              "name": "latitude",
              "type": "float",
              "required": false
            },
            {
-              "id": 14,
+              "id": 15,
              "name": "longitude",
              "type": "float",
              "required": false
            }
          ]
        },
        "element-required": true
      },
      "required": true
    },
    {
-      "id": 15,
+      "id": 7,
      "name": "person",
      "type": {
        "type": "struct",
        "fields": [
          {
            "id": 16,
            "name": "name",
            "type": "string",
            "required": false
          },
          {
            "id": 17,
            "name": "age",
            "type": "int",
            "required": true
          }
        ]
      },
      "required": false
    }
  ],
  "schema-id": 0,
  "identifier-field-ids": [
    2
  ]
}
```

**Comment by Fokko** [comment]
Hey @sebpretzer Thanks for reaching out. The IDs are re-assigned in a pre-order fashion. This is to make sure that the IDs are set correctly when you first create a table. After creating the table, the schema should be automatically be updated.

In general the APIs are designed in such a way that you don't have to set field-ids:

```python
with table.update_schema() as update:
    update.add_column("retries", IntegerType(), "Number of retries to place the bid")
```

Let me know if this answers the question, or if there is anything unclear.

**Comment by sebpretzer** [comment]
Ah, that makes sense. I assume the re-assigning is happening [here](https://github.com/apache/iceberg-python/blob/03caee20570cd7eabd2a5a9ee7341a154b818ca1/pyiceberg/table/metadata.py#L407). 

When initializing a `Schema`, it seems like it is required that have to set a field-id. This fails:
```python
Schema(NestedField(name="retries", field_type=IntegerType()))
```

Would it be possible to improve the user experience by either auto-populating field-ids in pre-order if not provided, or by failing on initialization when the field-ids are not in pre-order?

**Comment by sebpretzer** [comment]
@Fokko To follow up, we have fixed this internally ourselves with something similar to below:
```python
from pydantic import BaseModel, field_validator
from pyiceberg.schema import Schema, assign_fresh_schema_ids

class FooBarModel(BaseModel)
    iceberg: Schema

    @field_validator("iceberg")
    def field_ids_in_preorder(cls, v: Schema) -> Schema:
        if v != assign_fresh_schema_ids(v):
            raise ValueError("Schema ids not in preorder")
        return v
```
It places a bit more burden on users to properly order the field ids, but the schema will no longer change underneath them. If you want something similar upstream in `Schema`, I am happy to take a crack at it.
