### ISSUE TITLE
bug: The current snapshot with id 0 will be skip. 

### ISSUE THREAD

**Issue by ZENOTME** [apache/iceberg-python#232]
I find that the current snapshot with id 0 will be ignored. It caused by following if statement:

https://github.com/apache/iceberg-python/blob/cf31507a6f7e50b2b1f11364befe65b1124324f3/pyiceberg/table/__init__.py#L812

In this if statement, the 0 and None both be skipped.

**Comment by Fokko** [comment]
That's indeed a bug, thanks for spotting this @ZENOTME. Are you interested in creating a PR to fix it?

**Comment by MehulBatra** [comment]
I will take care of it.
