### ISSUE TITLE
Support get partition table with filter

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#24]
### Feature Request / Improvement

Migration of issue https://github.com/apache/iceberg/issues/8619

**Comment by puchengy** [comment]
Hello @Fokko, here is my use case:
1. Given a table, find out all the partitions it has.
2. Given a partition filter, check if such partition exist in the table.
Thank you!

**Comment by Fokko** [comment]
@puchengy The problem with Iceberg is that the partition is more of a logical concept, rather than a physical path like in a Hive table. What do you think of passing in a predicate, and letting the Airflow sensor pass if the is more than one row?

**Comment by puchengy** [comment]
> What do you think of passing in a predicate, and letting the Airflow sensor pass if there are rows?

@Fokko That works. This is actually what we are doing (but for legacy_python) https://github.com/pinterest/iceberg/commit/7d8d65d7ae8ed559052444928f00c36a11fe8f7d

Would this be something we can implement in the upstream? Thanks

**Comment by puchengy** [comment]
@Fokko gentle ping, thanks ^

**Comment by Fokko** [comment]
@puchengy Yes, certainly. Would this be something that you're interested in working on? From the snapshot, we can load the manifest list, and from there the manifests themselves, which contain the partition information

**Comment by puchengy** [comment]
@Fokko Yes, I can help. Thanks.

**Comment by pp-akursar** [comment]
I was looking for something comparable to spark's [partitions](https://iceberg.apache.org/docs/latest/spark-queries/#partitions) metadata table, which lets me do something like this

    SELECT partition, last_updated_snapshot_id, last_updated_at
    FROM prod.db.table.partitions
    WHERE partition.foo='bar'

to determine if and when a partition was updated, and came across this issue. It sounds like this could be provided by this Feature Request if it includes a ManifestReader with filtering features like the linked code in legacy_python. Is that correct? If not, I will try to raise as a separate issue.

**Comment by syun64** [comment]
Partitions table was added in:  https://github.com/apache/iceberg-python/pull/603
