### ISSUE TITLE
Support partial overwrites

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#268]
### Feature Request / Improvement

The current `Table.overwrite(pa.Table, BooleanExpression)` allows us to overwrite parts of the table that match the predicate. Currently only `AlwaysTrue()` is supported, which means a full overwrite.

**Comment by whynick1** [comment]
@Fokko if nobody is already looking at this, would love to try and take a stab at this?

**Comment by Fokko** [comment]
@whynick1 This should be done once https://github.com/apache/iceberg-python/issues/554 is in. Would you like to provide one of the metadata tables? See https://github.com/apache/iceberg-python/issues/511

**Comment by Fokko** [comment]
Closing this since it is a duplicate of #511. A partial overwrite is essentially a delete + append.

**Comment by whynick1** [comment]
> @whynick1 This should be done once #554 is in. Would you like to provide one of the metadata tables? See #511

@Fokko In that case, can I take https://github.com/apache/iceberg-python/issues/554, if not I am happy to work on #511 too.
