### ISSUE TITLE
InMemory Catalog

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#293]
### Feature Request / Improvement

Feature Request: InMemory Catalog implementation for Python Iceberg. For testing, prototyping, and generally playing around with Iceberg. 

It would be great to have a catalog implementation in-memory, and possibly write to local file system instead of s3. This would lower the barrier to entry to use the python iceberg library. 

There's currently a `NoopCatalog` which is used for loading [`StaticTable`](https://github.com/apache/iceberg-python/blob/1befad70bb72e649ec07431a43972aa2cd0cc0da/pyiceberg/table/__init__.py#L1010C7-L1010C18)

There's also a [`InMemoryCatalog`](https://github.com/apache/iceberg-python/blob/1befad70bb72e649ec07431a43972aa2cd0cc0da/tests/catalog/test_base.py#L61) implementation already used for testing. We can use this as the basis for implementation. 
 

Inspired by [Trino's Memory connector](https://trino.io/docs/current/connector/memory.html)

**Comment by Fokko** [comment]
Forwarding my comment here as well: https://github.com/apache/iceberg-python/pull/289#issuecomment-1903442816

Maybe we should add this to the documentation of the SqlCatalog as well: 

```python
def catalog_memory(warehouse: Path) -> Generator[SqlCatalog, None, None]:
    props = {
        "uri": "sqlite+pysqlite:///:memory:",
        "warehouse": f"file://{warehouse}",
    }
```

https://github.com/apache/iceberg-python/blob/1befad70bb72e649ec07431a43972aa2cd0cc0da/tests/catalog/test_sql.py#L69-L73

The `warehouse` directory is where the files are stored.

**Comment by asheeshgarg** [comment]
@Fokko 
Is this https://github.com/apache/iceberg/pull/4518 supported as part of pycieberg?

**Comment by kevinjqliu** [comment]
@Fokko 
Didn't know the in-memory sqlite option was available! That's awesome.
I was able to read/write using the `SqlCatalog`. Metadata is saved in memory using sqlite and data is saved on disk.

Pulling out [your comment in #289](https://github.com/apache/iceberg-python/pull/289#issuecomment-1903442816)

> Thanks for working on this @kevinjqliu. The issues was created a long time ago, before we had the SqlCatalog with sqlite support. Sqlite can also work [in memory](https://www.sqlite.org/inmemorydb.html) rendering the `InMemoryCatalog` obsolete. Having two in-memory implementations in the codebase adds additional complexity in the codebase. My suggestion would be to replace the MemoryCatalog with the SqlCatalog. WDYT?


I agree that we don't need 2 in-memory catalog implementations. Let me see if I can repurpose #289

**Comment by kevinjqliu** [comment]
Looks like there's also a `InMemoryCatalog` in the Java lib
lgithub.com/apache/iceberg/blob/0f509d2d678db2d7322dafded58ec0ca6d7fb268/core/src/main/java/org/apache/iceberg/inmemory/InMemoryCatalog.java#L61

**Comment by kevinjqliu** [comment]
@Fokko I took some time to think this over. I understand your concern regarding 2 in-memory catalog implementations. The 2 implementations are just 2 different ways to achieve the same outcome; using `Sqlite`'s in-memory database is an implementation detail.

I'm leaning towards having `InMemoryCatalog` as an option especially since there is a Java version of it already. 

I think there's value in storing the pure Python Object in memory and making it easily accessible. The `Sqlite`'s in-memory database is another level of indirection which can be difficult to reason about the internals of Iceberg.

**Comment by Fokko** [comment]
@kevinjqliu Alright, that's fair, I just wanted to make sure that we considered the option before making the `InMemory` one public 👍

**Comment by Fokko** [comment]
I must admit that I'm second-guessing the decision to add another catalog. This mostly comes from the recent discussions on the Java side where catalogs are being removed to avoid further proliferation.

**Comment by kevinjqliu** [comment]
@Fokko thats fair. I'll see if there are features in the PR I can pull out. We can leave the `InMemory` catalog under `tests/` for now.
