### ISSUE TITLE
Inconsistency in catalog.list_tables Behavior Across Python and Java: Returns Non-Iceberg Tables in Python Only

### ISSUE THREAD

**Issue by HonahX** [apache/iceberg-python#314]
### Feature Request / Improvement

I noticed that in python, `hive`, `glue` and `dynamo` list all tables, including non-Iceberg ones, in the namespace
https://github.com/apache/iceberg-python/blob/acc934fb76aa6c6e2e32b60c8a99f9e2b2c627dd/pyiceberg/catalog/hive.py#L488-L504
https://github.com/apache/iceberg-python/blob/acc934fb76aa6c6e2e32b60c8a99f9e2b2c627dd/pyiceberg/catalog/glue.py#L584-L613

However, in java, we apply a filter to only return Iceberg tables in the given namespace:
[GlueCatalog.listTables](https://github.com/apache/iceberg/blob/4e62b58f04aba4ccc2a2a846494b478d3b03f58f/aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java#L318-L322)
[HiveCatalog.listTables](https://github.com/apache/iceberg/blob/5487c17474f5ed2b507af369e3540fcd46aff9e2/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java#L139)

I forgot if we discussed this before: Why do we choose to include non-iceberg tables in the result in python?

cc @Fokko

**Comment by mark-major** [comment]
I'd like to work on this, if it's possible

**Comment by kevinjqliu** [comment]
@mark-major sure thing, assigned to you
