### ISSUE TITLE
Python: Add before- and after operations to `PreOrderSchemaVisitor`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#32]
### Feature Request / Improvement

In the `SchemaVisitor`: https://github.com/apache/iceberg/blob/c68abfc9fd3956077b43aba20441f089bb8b93d6/python/pyiceberg/schema.py#L345-L374

Those are missing in the `PreOrderSchemaVisitor`: https://github.com/apache/iceberg/blob/c68abfc9fd3956077b43aba20441f089bb8b93d6/python/pyiceberg/schema.py#L401

https://github.com/apache/iceberg/blob/c68abfc9fd3956077b43aba20441f089bb8b93d6/python/pyiceberg/schema.py#L785

**Comment by MehulBatra** [comment]
Looking into it.
