### ISSUE TITLE
Add example of using PyIceberg with minimal external dependencies

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#326]
### Feature Request / Improvement

With #299 resolved, let's add an example to show working with Iceberg using minimal external dependencies. 

Get started with Iceberg using the local filesystem and a simple catalog.
`Local Filesystem` + `SqlCatalog`

## Catalog config
```
from pyiceberg.catalog.sql import SqlCatalog

catalog_path = "/tmp/warehouse/pyiceberg.db"
warehouse_path = "/tmp/warehouse/"
catalog = SqlCatalog("default", **{
    "uri": f"sqlite:///{catalog_path}",
    "warehouse": f"file://{warehouse_path}",
})
```

Note that, the `/tmp/warehouse/` folder needs to exist first.

## Create a new table and write to it
https://github.com/apache/iceberg-python/blob/main/mkdocs/docs/api.md#write-support
With Python console / Jupyter notebook

## Query the table with `pyiceberg` CLI
Configure the `~/.pyiceberg.yaml` file,
```
catalog:
  default:
    uri: sqlite:////tmp/warehouse/pyiceberg.db
    warehouse: file:///tmp/warehouse/
```

Run `pyiceberg` CLI:
`pyiceberg list`
`pyiceberg describe`

**Comment by bitsondatadev** [comment]
> Note that, the /tmp/warehouse/ folder needs to exist first.

@kevinjqliu what do you think of managing the file creation/deletion by default

```python
import tempfile
from pyiceberg.catalog.sql import SqlCatalog

with tempfile.TemporaryDirectory(delete=True) as warehouse_path:
    catalog_path = f"{warehouse_path}/pyiceberg.db"

    catalog = SqlCatalog("default", **{
      "uri": f"sqlite:///{catalog_path}",
      "warehouse": f"file://{warehouse_path}",
    })

    print('created catalog: ', catalog)
```

**Comment by kevinjqliu** [comment]
that's a great idea! 

I'm thinking of adding this in [Getting started with PyIceberg](https://github.com/apache/iceberg-python/blob/main/mkdocs/docs/index.md)
WDYT? @bitsondatadev @Fokko

**Comment by bitsondatadev** [comment]
Yeah I want to sprinkle this literally everywhere in the docs so please go for it. I think this will be my preferred way of teaching Iceberg.

**Comment by kevinjqliu** [comment]
++, this lowers the barrier to entry by a lot. It's a lot of work to spin up docker/s3/minio integration and hive 😱!

**Comment by kevinjqliu** [comment]
Added example to "getting started" in #361 

Didn't use `tempfile` there since I think it's useful to be able to see what data and metadata files are generated by Iceberg.
