### ISSUE TITLE
Have a better error message in case of a schema mismatch

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#328]
### Feature Request / Improvement

When a schema doesn't match, we currently just present the two schema's. It would be great to explicitly tell the user what the difference is between the schemas.

**Comment by MehulBatra** [comment]
@Fokko If the situation allows I would love to take a shot at it.

**Comment by Fokko** [comment]
@MehulBatra Thanks, but I think this was already fixed by https://github.com/apache/iceberg-python/pull/352
