### ISSUE TITLE
What is Table Identifier? 

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#341]
### Question

In `test_base.py` the Table Identifier, `TEST_TABLE_IDENTIFIER`, is a tuple of 4 elements 
```
TEST_TABLE_IDENTIFIER = ("com", "organization", "department", "my_table")
```

In most other places, the Table identifier is either a tuple of 2 elements `(database_name, table_name)` or a string with 2 parts, `database_name.table_name`.
See [more examples](https://github.com/search?q=repo%3Aapache%2Ficeberg-python+%22identifier+%3D%22+path%3A%2F%5Etests%5C%2F%2F&type=code) 

In #289, I wanted to implement the `location` for in-memory catalog the [same way as other catalog implementations](https://github.com/search?q=repo%3Aapache%2Ficeberg-python+%22location+%3D+self._resolve_table_location%28location%2C+database_name%2C+table_name%29%22&type=code), by using the `_resolve_table_location` function.
```
location = self._resolve_table_location(location, database_name, table_name)
```  

However, due to the Table Identifier being a 4-element tuple, I cannot parse the database name using `identifier_to_database_and_table`
```
database_name, table_name = self.identifier_to_database_and_table(identifier)
``` 

**What is the proper spec of Table Identifier? And what part of it represents the `database_name`?**

In Java implementation, [`TableIdentifier`](https://github.com/apache/iceberg/blob/9de693f1e7f46024f47cdc971d8603fd76d87705/api/src/main/java/org/apache/iceberg/catalog/TableIdentifier.java#L28) is made up of two parts, the `namespace` and the `name`, where
[`Namespace`](https://github.com/apache/iceberg/blob/9de693f1e7f46024f47cdc971d8603fd76d87705/api/src/main/java/org/apache/iceberg/catalog/Namespace.java) is a list of string.

**Comment by Fokko** [comment]
Hey @kevinjqliu As you already concluded, most catalogs only use two parts, one namespace and the table name. The REST catalog supports hierarchical namespaces, and of course we can add it to the InMemory one as well.

> What is the proper spec of Table Identifier? And what part of it represents the database_name?

The last element represents the table name, and everything in front of it are the name-spaces.

**Comment by kevinjqliu** [comment]
So if I understand correctly, TableIdentifier consists of the namespace and the table name. Namespace can be multiple parts, for example ("com"."apache"."iceberg") or "com.apache.iceberg". And table name is 1 word, i.e. "foo".

If this is the case, is "database name" part of the namespace and possibly the last element of the namespace? 
There are a [few references](https://github.com/search?q=repo%3Aapache%2Ficeberg-python%20database_name&type=code) to "database name" in the codebase and I want to understand the relation. 
Particularly, the `_resolve_table_location` function exposed by `[catalog/__init__.py](https://github.com/apache/iceberg-python/blob/a4856bc2eadf90ac85dec96d4502ca3517bb1bb5/pyiceberg/catalog/__init__.py#L535)`

> The REST catalog supports hierarchical namespaces
What is the definition of "hierarchical namespaces" here?

**Comment by kevinjqliu** [comment]
Answering my own questions above. 

A TableIdentifier is in the form of (namespace, ..., database_name, table_name). `table_name` is the last element of the tuple. `database_name` is the second to last element of the tuple. everything else is part of the namespace name. 
TableIdentifier can be represented as either tuple or a single string separated by `.` 

A namespace can be "hierarchical" because it has multiple levels, such as (foo) or (foo, bar) or (foo, bar, baz).
