### ISSUE TITLE
`pyiceberg.io.pyarrow.write_file` does not take into account compression settings

### ISSUE THREAD

**Issue by jonashaag** [apache/iceberg-python#345]
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

I expected `table.append()` to take my `write.parquet.compression-codec` etc settings into account but it looks like no settings are passed to `ParquetWriter`: https://github.com/apache/iceberg-python/blob/29db67fef819f2df0b30ea7decb10537f5a22eef/pyiceberg/io/pyarrow.py#L1729

For my data this means a 5x size increase compared to using zstd level 3

**Comment by Fokko** [comment]
@jonashaag Thanks for reporting this, and you're right. The settings are currently not taken into account. Are you interested in contributing this to the project? 

We need to pass in the correct string to the `ParquetWriter`: https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetWriter.html And also set the compression level.

**Comment by jonashaag** [comment]
Yes happy to. Can you point me to some other places where the config is read and passed around etc?

**Comment by Fokko** [comment]
@jonashaag Sure thing! This is where we need to pass in the configuration:

https://github.com/apache/iceberg-python/blob/a4856bc2eadf90ac85dec96d4502ca3517bb1bb5/pyiceberg/io/pyarrow.py#L1713-L1758

The `table.properties` contains the configuration option. Today we only support writing Parquet files, therefore we want to fetch the `write.parquet.compression-codec` property that `∈ {zstd, gzip, snappy}` which corresponds with the properties in Arrow. Next, we also need to get `write.parquet.compression-level` to set the level.

I would just create a function to extract the relevant properties and then pass the into the writer. Let me know if this helps or if you have any other questions.

**Comment by jonashaag** [comment]
I think the REST catalog ignores the `write.parquet.compression-codec` option. No matter what options I set for the catalog, it always responds here https://github.com/apache/iceberg-python/blob/a4856bc2eadf90ac85dec96d4502ca3517bb1bb5/pyiceberg/catalog/rest.py#L472 with
```
'write.parquet.compression-codec': 'zstd'
```
even if I explicitly set `write.parquet.compression-codec` in the `properties` a few lines above.

I'll submit a patch that passes the right arguments to PyArrow but currently we can't support any other compression options for the REST catalog it seems.

**Comment by jonashaag** [comment]
Update: Hm, now it doesn't seem to be the case anymore. Not sure what happened there...

**Comment by Fokko** [comment]
@jonashaag The REST catalog sets the property as a default one, the other ones don't. If no property is set, it should default to zstd similar to Java.

**Comment by Fokko** [comment]
Fixed in https://github.com/apache/iceberg-python/pull/358
