### ISSUE TITLE
Support reading and writing snapshot properties

### ISSUE THREAD

**Issue by brianfromoregon** [apache/iceberg-python#367]
### Feature Request / Improvement

snapshots.py has a Snapshot and Summary class but they don't seem to be user facing. I'd like to read/write custom properties in the snapshot's summary map. When writing a property, it should be possible to do so atomically with a data write (in same snapshot)

**Comment by Fokko** [comment]
Hey @brianfromoregon, I agree. For writing, I left a comment in https://github.com/apache/iceberg-python/issues/368 For reading, I think we're missing some documentation since it is already possible:

```python
if snapshot := tbl.current_snapshot():
    snapshot.summary.get("watermark:raw.log_source")
```

**Comment by Gowthami03B** [comment]
@brianfromoregon @Fokko can I take a stab at this?

**Comment by Gowthami03B** [comment]
https://github.com/apache/iceberg-python/pull/419

**Comment by syun64** [comment]
Completed by #419
