### ISSUE TITLE
Allow non-stringly typed table properties

### ISSUE THREAD

**Issue by jonashaag** [apache/iceberg-python#376]
### Feature Request / Improvement

Currently table properties like `write.parquet.compression-level` need to be stringly typed in PyIceberg. Should we allow for other types as well?

**Comment by Fokko** [comment]
@jonashaag Can you give an example? Table properties are encoded as strings by default.

**Comment by jonashaag** [comment]
See the example in my post. The pydantic Schema doesn't allow for non strings currently

**Comment by Fokko** [comment]
But we convert it to an int when setting the level?

**Comment by jonashaag** [comment]
Do you think we should automatically convert them to a string if safe? It is just really awkward to set eg the compression level as a string

**Comment by Fokko** [comment]
Yes, that's what we are doing here:

https://github.com/apache/iceberg-python/blob/853a77c5d24280a1048ebcef9a9bfe0cedb642ca/pyiceberg/io/pyarrow.py#L1766-L1773

> It is just really awkward to set eg the compression level as a string

It is a string map, so I don't think we have any other options.

**Comment by jonashaag** [comment]
> convert them to a string

The code you are showing converts them *from* a string.

I meant the other end:

```
create_table(..., properties={"write.parquet.compression-level": 42})
```

**Comment by Fokko** [comment]
@jonashaag Ahh, thanks, it already felt like I was missing a piece. We should accept everything that can coerce into a string. I like to follow the idea of being liberal in what you accept and being strict when writing.

**Comment by Fokko** [comment]
@jonashaag is this something that you're interested in contributing? :)

**Comment by kevinjqliu** [comment]
@jonashaag this should work now!
