### ISSUE TITLE
Add support for writing `large_string` and `int16`

### ISSUE THREAD

**Issue by jonashaag** [apache/iceberg-python#378]
### Feature Request / Improvement

Currently we don't support `large_string` (default string type written by eg. Polars) and `int16`

**Comment by Fokko** [comment]
I think we can support large-string today.

`int16` is a bit more interesting case since it is not natively supported by Iceberg.

**Comment by jonashaag** [comment]
I have a locally patched version that simply maps `large_string` to `string` but I got problems with batches > 2 GiB. Not sure if that's related. I'm not forcing batches to be <= 2 GiB upon ingestion

**Comment by syun64** [comment]
> I have a locally patched version that simply maps `large_string` to `string` but I got problems with batches > 2 GiB. Not sure if that's related. I'm now forcing batches to be <= 2 GiB upon ingestion
> 
> ("Batches" = individual calls to `table.append()`)

@jonashaag could you describe the problem you are seeing with the larger batches with this approach? Just so we have it on record on this issue
