### ISSUE TITLE
duckdb don't seems to read the iceberg table

### ISSUE THREAD

**Issue by djouallah** [apache/iceberg-python#387]
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

ok, I generated some data using the new release which is a fantastic works , but duckdb don't seems to understand it

https://colab.research.google.com/drive/1EjffJO75-8Rj4V0MGKUsoFHDOGgicKgK#scrollTo=OPH-dWMUlbhJ

**Comment by Fokko** [comment]
Thanks for reporting this, including an example. It looks like there is an issue with the local URI's. Let me dig into this right away!
