### ISSUE TITLE
Conversion between date/timestamp(tz) and integer for avro reader/writer

### ISSUE THREAD

**Issue by jqin61** [apache/iceberg-python#398]
### Question

Hi I was trying to understand whether there is any special design initiative for:
1. The Python representation of partition of datetime-related type is integer. For example:
```
iceberg_table.current_snapshot().manifests(iceberg_table.io)[0].fetch_manifest_entry(iceberg_table.io)[0].data_file.partition
``` 
would show DataFile instance having partition as 
```
Record[SNAPSHOT_DATE=18628]
```

Since DataFile class is a Python object, would it make more sense to represent it using native Python date/datetime?

2. As a result, conversion between date/timestamp(tz) and integer stays outside of avro reader/writer. For example, we have the source code of :
```
@dataclass(frozen=True)
class DateWriter(Writer):
    def write(self, encoder: BinaryEncoder, val: int) -> None:
        encoder.write_int(val)
```
which can only take int as input.

I asked because I was trying to implement partition write support and during writing the manifest list, I instantiated the DataFile using partition = Record(field=raw date-typed Python object) which breaks the avro writer for writing the manifest file. So I wonder whether I should:

1. Do the conversion from date -> into before instantiating the DataFile's partition field or maybe 
2. Change the avro DateWriter to handle the date-integer conversion (and do this for avro reader as well).

**Comment by Fokko** [comment]
Thanks for raising this @jqin61.

The date is a logical type, where the integer represents the days since 1-1-1970. To public APIs, we should accept `datetime.date` for convenience. Then we should convert it internally:

https://github.com/apache/iceberg-python/blob/7a1fe28df38bfdc69166915dca49cfde660853bf/pyiceberg/utils/datetime.py#L55-L57

Onto how to resolve this. I would lean to 1. since this is not publically exposed. We can just keep it an integer internally (this makes comparisons easier).

**Comment by jqin61** [comment]
Thank you for the explanation! Will move forward with the first option as instructed.

**Comment by Fokko** [comment]
Thanks @jqin61 🙌  If we can split out this kind of task into a separate PR would be preferred. This way we keep the partitioned writes PR a bit manageable :)

**Comment by jqin61** [comment]
Yep yep totally agree, I am splitting one portion of the partitioned write for the features of partition path generation and PartitionKey class into a separate PR currently. Will submit soon.
