### ISSUE TITLE
make to_duckdb accept multiple tables 

### ISSUE THREAD

**Issue by djouallah** [apache/iceberg-python#408]
### Feature Request / Improvement

currently it seems 
`con =catalog.load_table('aemo.scada').scan().to_duckdb(table_name="scada") `
accept only 1 table, it will be nice to have something like
`con =catalog.load_namespace('aemo').scan().to_duckdb()`
which will expose the whole database to duckdb in one go

**Comment by Fokko** [comment]
Thanks for reporting this. I like it! We need to have support for lazy datasets before this becomes feasible.

**Comment by djouallah** [comment]
is there a way to load two tables, it seems you can only Query 1 table at the time ?

**Comment by ischwart1** [comment]
@djouallah 

Apparently you can pass a duckdb connection to `to_duckdb()`, that way you can chain many table together:

```python

with (
    catalog.load_table(f"{config.lake.namespace}.{config.bronze.map_id}")
    .scan()
    .to_duckdb("bronze_map_id") as con1
):
    with (
        catalog.load_table(f"{config.lake.namespace}.{config.bronze.mob}")
        .scan()
        .to_duckdb("bronze_mob", con1) as con2
    ):
        con2.sql("""--sql
        with mob as (
            select unnest(mobs).link as link from bronze_map_id
        ),
        links as (
            select
                regexp_extract(link, '/mob/(\\d+)', ['mob_id']).mob_id as mob_id,
                count(*) as count
            from
                mob
            group by
                link
        )
        select
                links.mob_id, name, count
        from
            links
        join
            bronze_mob
        on
            links.mob_id = bronze_mob.id
        """).show(max_width=1000)

```
