### ISSUE TITLE
glue.endpoint config implementation?

### ISSUE THREAD

**Issue by sebpretzer** [apache/iceberg-python#414]
### Feature Request / Improvement

@HonahX @Fokko I was wondering if the `glue.endpoint` config variable could be implemented? Similar to how [s3.endpoint has already been implemented in pyiceberg](https://github.com/apache/iceberg-python/blob/e9e265a1878a55a4385580bf800382fd75c912c9/pyiceberg/io/__init__.py#L49), and how [glue.endpoint has been implemented in iceberg](https://github.com/apache/iceberg/blob/053d54172fd903be9eda78957f3cbd3aadef1f7b/aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java#L103). I am trying to integrate my tests completely with a moto server, but that cannot be done without routing glue calls to a separate endpoint afaik. I have a hack in my codebase for now, so this request is not urgent. 

I *think* this would mainly impact [the boto glue client](https://github.com/apache/iceberg-python/blob/e9e265a1878a55a4385580bf800382fd75c912c9/pyiceberg/catalog/glue.py#L267) (plus tests and documentation). If that is the extent of changes, I am happy taking a crack at implementing it.

I know you are all mid-release, and there are [other glue namespaced config variables that you may want to do all at the same time](https://github.com/apache/iceberg/blob/053d54172fd903be9eda78957f3cbd3aadef1f7b/aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java#L58-L95), so I leave it to you if this is something worth pursuing. 

Thanks!

**Comment by Fokko** [comment]
Hey @sebpretzer thanks for reaching out! I think it would be a good addition. We didn't port all the configuration upfront to make sure that we only port the relevant keys. It would be great if you could provide a PR. Feel free to tag me there.
