### ISSUE TITLE
Minimum Requirement of Data File Name in Apache Iceberg?

### ISSUE THREAD

**Issue by syun64** [apache/iceberg-python#429]
### Question

Hi folks, I was chatting with @jaychia the other day and we were both wondering about the importance of the file naming convention in Apache Iceberg. Currently, PyIceberg and Java code both seem to have slightly different logic in generating the unique data file name.

**(UriScheme)://(TableDataLocationPrefix)/(PartitionPath)/(FileName).(Extension)**

e.g.

**s3a://warehouse-dev/table/data/DATE=2024-01-20/00008-6616-9bc4befb-04af-4fb3-b3ac-1b32de91349a-00001.parquet**

1. PyIceberg: https://github.com/apache/iceberg-python/blob/3a158957b692c7a962bee46905ea1b64c5bffd5e/pyiceberg/table/__init__.py#L2321 
2. Java Iceberg: https://github.com/apache/iceberg/blob/a582968975dd30ff4917fbbe999f1be903efac02/core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java#L92-L101

The partition 'path' undeniably has a very important significance in Iceberg. However, the data file paths/names are all stored in in the manifest files, and hence one could argue that the specific logic used to generate the file name is more a convention than a requirement. If the only requirement is that the data file name is unique, it could open up more options in leveraging external engines in parallelizing writes, and then using the written files to write the manifests, and upwards.

So, what is the requirement for the data **file name** in Apache Iceberg? Is it simply that they are unique?

**Comment by Fokko** [comment]
Thanks @syun64 for raising this!

> The partition 'path' undeniably has a very important significance in Iceberg. However, the data file paths/names are all stored in in the manifest files, and hence one could argue that the specific logic used to generate the file name is more a convention than a requirement. If the only requirement is that the data file name is unique, it could open up more options in leveraging external engines in parallelizing writes, and then using the written files to write the manifests, and upwards.

This is true with Iceberg, contrary to the classical Hive partitions, the partition is just to help the user, but it is not a requirement as you already explained.

The requirements is that we can trace where the data belongs to. For example, the partition information is not required, but makes it possible to link a parquet file to a partition without looking at the metadata. For the filename, it is more about seeing which write operation created the file. 

Looking at the current code, I think it would be good to re-use the commit-uuid as the write-uuid: https://github.com/apache/iceberg-python/pull/437

Does this help?

**Comment by syun64** [comment]
I like the idea! This is definitely helpful, and I think this opens up a lot more options when looking to use other engines in parallelizing writes.
