### ISSUE TITLE
`catalog.create_namespace(...)` throws both 404 and 409 which is unintuitive

### ISSUE THREAD

**Issue by seunggs** [apache/iceberg-python#430]
### Apache Iceberg version

0.5.0 (latest release)

### Please describe the bug 🐞

I'm actually using the 0.6.0rc4 version, but that shouldn't matter in this case.

During the ingestion process, I'm running parallel jobs with the following code:
```
# Create a namespace if it doesn't exist
try:
    catalog.create_namespace(ns_name)
    self.logger.info(f"Namespace '{ns_name}' created")
except NamespaceAlreadyExistsError:
    self.logger.info(f"Namespace '{ns_name}' already exists")
```

The first call goes through as expected since no namespace currently exists. But the second parallel call fails and throws both 404 and 409:
```
self._handle_non_200_response(exc, {404: NoSuchNamespaceError, 409: NamespaceAlreadyExistsError})
```

The expected behavior is to only throw 409 since 404 `NoSuchNamespaceError` doesn't make sense in the context of  namespace creation.

**Comment by Fokko** [comment]
@seunggs The REST catalog can create hierarchical namespaces. But even if you run:

```python
catalog.create_namespace(('finance', 'invoicing'))
```

it will create the parent namespace, so I think we can remove `NoSuchNamespaceError`. Does it throw the error?

**Comment by seunggs** [comment]
Hi @Fokko, hierarchical namespaces are not really an issue for me - the issue is attempting to create the same namespace from parallel calls. I have an ingestion pipeline that runs multiple jobs in parallel (e.g. `orders`, `customers`, and `payments` csv's). Each of these jobs runs the code above in parallel and the first attempt to create a non-existent namespace succeeds, but the other two calls throw an error.

This is expected if it just threw 409 `NamespaceAlreadyExistsError`. But it throws both 404 and 409 which I think is surprising. 

So yes, long story short, I think it's best we removed `NoSuchNamespaceError` unless there's something I'm missing that requires this.

**Comment by Fokko** [comment]
@seunggs I agree that we can remove the `NoSuchNamespaceError`, are you interested in creating a PR here?
