### ISSUE TITLE
Empty iceberg table created with PyIceberg in AWS Glue misses location and schema

### ISSUE THREAD

**Issue by zartstrom** [apache/iceberg-python#435]
### Apache Iceberg version

None

### Please describe the bug 🐞

I want to create an empty [Iceberg](https://iceberg.apache.org/) table with [PyIceberg](https://py.iceberg.apache.org/) in AWS Glue. The snippet below creates the table, but does not show the location and schema information in AWS Glue.
What am I missing?

![Missing location](https://i.stack.imgur.com/a8imh.png)

![Missing schema](https://i.stack.imgur.com/1t1Oy.png)

```python
from pyiceberg.catalog import load_catalog
from pyiceberg.schema import Schema
from pyiceberg.types import TimestampType, StringType, NestedField

schema = Schema(
    NestedField(field_id=1, name="datetime", field_type=TimestampType()),
    NestedField(field_id=2, name="job_id", field_type=StringType()),
    NestedField(field_id=3, name="result", field_type=StringType()),
    NestedField(field_id=4, name="description", field_type=StringType()),
)

if __name__ == "__main__":
    catalog = load_catalog(
        "default",
        **{
            "type": "glue",
        },
    )

    catalog.create_table(
        identifier=f"manually_created.my_test_table",
        schema=schema,
        location="s3://my_test_bucket/my_test_table",
    )
```
with version pyiceberg==0.5.1.

**Comment by Fokko** [comment]
@zartstrom Thanks for raising this! 👍 

I think this has been fixed in https://github.com/apache/iceberg-python/pull/288. Can you try this by installing [the latest RC `pip install==0.6.0rc4`](https://pypi.org/project/pyiceberg/0.6.0rc6/).

**Comment by zartstrom** [comment]
Hi @Fokko thank you a lot for your hint to #288 .
I installed version `0.6.0rc4` and location and schema appear as expected!
