### ISSUE TITLE
"CREATE TABLE (REPLACE TABLE) ... AS SELECT" Support

### ISSUE THREAD

**Issue by syun64** [apache/iceberg-python#438]
### Feature Request / Improvement

In Spark SQL, we have the ability to combine the table overwrite using AS SELECT statement, with create_table or replace_table, as an atomic operation. [(CTAS, RTAS)](https://github.com/apache/iceberg/blob/1854d08a68c719f8a56dcf9e8e61dbdccbd19346/docs/docs/spark-ddl.md?plain=1#L89)

Do we intend to support this feature with the same atomicity guarantee in PyIceberg?

Since the PyIceberg client is in charge of writing out the manifests and constructing the new table metadata, I think it is technically possible. Would we just add 

`as_select: pa.Table = None`

as an optional parameter to **create_table** and **replace_table** and add a snapshot update with full table static overwrite to the new table metadata?

**Comment by Fokko** [comment]
Duplicate of https://github.com/apache/iceberg-python/issues/281

**Comment by syun64** [comment]
> Duplicate of #281

This was my bad attempt at decoupling the introduction of REPALCE TABLE support from the discussion of how we should support `... AS SELECT` semantic - but I think it's a bit too late for that now given how I've described the previous issue https://github.com/apache/iceberg-python/issues/281. I will bring these points back to the other issue.
