### ISSUE TITLE
Create table from plain Parquet files

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#445]
### Feature Request / Improvement

Today we can write to tables. During the write process we make sure that the schema is correct, and we collect column statistics during the write. It would be cool if we could also import existing Parquet files into a table, by extracting the schema, and fetching the statistics from the footer.

**Comment by syun64** [comment]
@Fokko would this process be similar to running the following steps?

1. create_table from PyArrow schema
2. invoking [add_files](https://iceberg.apache.org/docs/latest/spark-procedures/#add_files) migration procedure?

Potentially related Issue: https://github.com/apache/iceberg-python/issues/354

**Comment by HonahX** [comment]
@syun64 I think the logic of importing parquet files can be shared with `add_files` migration procedure. But for this issue we may want to do the creation and file import in a single transaction. In this way, if anything goes wrong, we won't leave users with an empty new table. 

I think needs something similar to [CreateTableTranscation](https://github.com/apache/iceberg/blob/715c9b90f537a215f38da5a8ddad19977222860b/core/src/main/java/org/apache/iceberg/Transactions.java#L50). WDYT?

**Comment by syun64** [comment]
Thank you for the explanation @HonahX . Yes that's really great insight. I'm definitely in support of a CreateTableTransaction, because that's what we will need to support `CREATE TABLE ... AS SELECT` semantics as well, where we stage the creation of the table until we create the data files and create the new snapshot that represents the table.

**Comment by HonahX** [comment]
> what we will need to support CREATE TABLE ... AS SELECT semantics as well...

Totally agree! I've created an issue to track this feature: https://github.com/apache/iceberg-python/issues/483

**Comment by Fokko** [comment]
Has been fixed in https://github.com/apache/iceberg-python/pull/506
