### ISSUE TITLE
Add support for custom header configs in RESTCatalog

### ISSUE THREAD

**Issue by geruh** [apache/iceberg-python#455]
### Feature Request / Improvement

I noticed that PyIceberg's RESTCatalog doesn't set custom header configs. This feature is in Java's implementation of the RESTCatalog, and was beneficial when building out my own testing catalog. For instance, my catalog may have a custom content-type header for POST requests. Therefore, my config endpoint can return a config containing this property:

```
{
  "defaults": {
    "header.content-type": "application/json-custom"
  },
  "overrides": {}
}
```

Which in the Java implementation will merge this in to the properties and add it as a header for all subsequent requests.

This logic can be followed in the RESTSessionCatalog init method: https://github.com/apache/iceberg/blob/4090a8860061f58748e3faa6804094f90d3575f3/core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java#L165

Is this something, we want to support in PyIceberg? I can add this if so.

@HonahX @Fokko

**Comment by Fokko** [comment]
Hey @geruh that's a great catch. I wasn't aware of that piece being missing. It would be great if you want to raise PR to add this 👍
