### ISSUE TITLE
Make the OAuth2 request scope configurable

### ISSUE THREAD

**Issue by flyrain** [apache/iceberg-python#462]
### Feature Request / Improvement

[OAuth2 Scope](https://oauth.net/2/scope/) is a mechanism to limit an application's access to a user's account. It can also be used to ask for more information like [openId user profile](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims)(id, name, email, etc). The user profile is useful for ACL checking in the server side. Currently PyIceberg hard-codes it to [`catalog`](https://github.com/apache/iceberg-python/blob/44948cd9bab78b509b6befc960b5f248b37f53fe/pyiceberg/catalog/rest.py#L99), which cannot support the use case above. I'd suggest to make it configurable. WDYT? cc @Fokko @danielcweeks @syun64 @RussellSpitzer 

Here is an http request example for better understanding.
```
curl --request POST \
  --url https://xxx.com/oauth2/token \
  --header 'Authorization: Basic xxx' \
  --header 'content-type: multipart/form-data' \
  --form grant_type=client_credentials \
  --form 'scope=openid offline corpds:ds:profile' \
```
Then the token in response will have the user profile like this:
```
corpds:ds:dsid=2321321, corpds:ds:email=abot44@xxx.com, corpds:ds:employeeType=D, corpds:ds:firstName=Bot1
```

**Comment by syun64** [comment]
Hi @flyrain thanks for raising this. I just took a look into the [Java code](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java#L181C80-L181C93), and the scope already seems to be configurable there.

Would you like to put up a PR here to make it similarly configurable?

**Comment by flyrain** [comment]
Thanks for conform, @syun64 . Glad it was taken care in Java.
