### ISSUE TITLE
Support OAuth2 Client credential flow

### ISSUE THREAD

**Issue by flyrain** [apache/iceberg-python#463]
### Feature Request / Improvement

It seems PyIceberg only supports OAuth2 [token exchange flow](https://datatracker.ietf.org/doc/html/rfc8693#name-token-exchange-request-and-). Here is the token response definition in the file rest.py. The field `issued_token_type` is only used by the token exchange flow. Can we support other flows? For example, one of the most used flow is [client credential flow](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4).  cc @danielcweeks @Fokko @syun64 @RussellSpitzer 
```
class TokenResponse(IcebergBaseModel):
    access_token: str = Field()
    token_type: str = Field()
    expires_in: int = Field()
    issued_token_type: str = Field()
```

**Comment by danielcweeks** [comment]
The client credential flow is already implemented: [see here](https://github.com/apache/iceberg-python/blob/82d88920aaa7cba8593e93b5df9f3a87b13c88da/pyiceberg/catalog/rest.py#L291)

**Comment by flyrain** [comment]
The client credential flow doesn't return a field `issued_token_type`.  PyIceberg failed at validation:
```
ValidationError: 1 validation error for TokenResponse
issued_token_type
  Field required [type=missing, input_value={'access_token': 'eyJhbGc... 'token_type': 'bearer'},
input_type=dict]
```
I assume there is not much difference for two flows in terms of request. The only change we may need to do is to make the field optional.
```
    issued_token_type: Optional[str] = None
```

**Comment by danielcweeks** [comment]
According to the [RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.3) it should be `token_type`, but we currently only support `bearer`.  The exchange does work, but assumes the type and ignores whatever is returned by the server.  Definitely could use improvement, but this does work currently with the above assumption.

**Comment by flyrain** [comment]
`token_type` are required by both flows in RFC. It is fine to be mandatory for both. The problem is the `issued_token_type`, The token exchange flow [RFC](https://datatracker.ietf.org/doc/html/rfc8693#name-token-exchange-request-and-) indicates it is required.
> `issued_token_type
REQUIRED. An identifier, as described in [Section 3](https://datatracker.ietf.org/doc/html/rfc8693#TokenTypeIdentifiers), for the representation of the issued security token.`

I will file a PR to make it optional since pyIceberg doesn't use it anyway.

**Comment by syun64** [comment]
Given that we've confirmed that Client Credentials flow is already supported, and we've fixed the current model to make attributes optional, is this issue good to close @flyrain ?

**Comment by flyrain** [comment]
Closed. Thanks @danielcweeks and @syun64 !
