### ISSUE TITLE
Support rewrite_manifests

### ISSUE THREAD

**Issue by nicor88** [apache/iceberg-python#465]
## Feature 
Not sure if this feature is already requested, but I would like to have support for rewriting manifests as in Spark.
Reference [rewrite_manifests](https://iceberg.apache.org/docs/latest/spark-procedures/#rewrite_manifests ) in spark

**Comment by Fokko** [comment]
@nicor88 It is recorded here https://github.com/apache/iceberg-python/issues/270 It is high on the list since with the fast-appends we're creating quite a bit of metadata.

**Comment by nicor88** [comment]
Ah thanks, I did a search on rewrite_manifests, somehow https://github.com/apache/iceberg-python/issues/270 didn't pop up.

I believe that this can be a duplicated then WDYT @Fokko ?

**Comment by Fokko** [comment]
I just updated the title to clarify it :) I think this is a duplicate indeed! Lets track it in the other issue
