### ISSUE TITLE
Integration test broken 

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#492]
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

As of [current commit](https://github.com/apache/iceberg-python/commit/36b56eb7bbc4cff91e4b9bfdf71ca0a7b8bbee5c) 3/2/2024

Error log:
```
>           assert spark_partition_for_justification == expected_partition_record
E           assert Record[timestamp_field_hour=464611] == Record[timestamp_field_hour=464603]
E             Full diff:
E             - Record[timestamp_field_hour=464603]
E             ?                                 ^^
E             + Record[timestamp_field_hour=464611]
E             ?                                 ^^

tests/integration/test_partitioning_key.py:771: AssertionError
```

Reproduce:
```
git checkout main
git pull
make test-integration
```

Possibly related to #453

**Comment by HonahX** [comment]
I also hit this today. I think this is because the spark session uses our local timezone when inserting timestamp values into that table. We may config the Spark Session to always use UTC timezone in `conftest.py`:
```python
spark = (
        SparkSession.builder.appName("PyIceberg integration test")
        .config("spark.sql.session.timeZone", "UTC")
        .config("spark.sql.extensions", "org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions")
        .config("spark.sql.catalog.integration", "org.apache.iceberg.spark.SparkCatalog")
        .config("spark.sql.catalog.integration.catalog-impl", "org.apache.iceberg.rest.RESTCatalog")
...
```

**Comment by kevinjqliu** [comment]
makes sense, I'm in PT (UTC-8) which matches the difference between `464603` and `464611`. 

Just ran `make test-integration` with the 
```
        .config("spark.sql.session.timeZone", "UTC")
```
and everything passed

**Comment by kevinjqliu** [comment]
Do you already have a PR out for the change? Or should I push one up?

**Comment by HonahX** [comment]
Could you please open one up? I can quickly merge that 😄 .

**Comment by kevinjqliu** [comment]
@HonahX opened #494
