### ISSUE TITLE
[feature request] easier API to set table properties 

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#502]
## Background
Currently, there are two ways to set table properties. 

1. in `create_table`, pass in `properties` as dictionary
https://github.com/apache/iceberg-python/blob/29fd42c9b81db2bde66b81ead231408dcd60661c/tests/catalog/test_sql.py#L168

2. using table `set_properties` transaction, pass in as key/value pair
https://github.com/apache/iceberg-python/blob/29fd42c9b81db2bde66b81ead231408dcd60661c/mkdocs/docs/api.md?plain=1#L483-L484

With the introduction of `TableProperties`, it would be great to make overriding table properties easier.
With the current methods, we can only override table properties during `create_table` since this is not valid python:
```
with table.transaction() as transaction: 
    transaction.set_properties(TableProperties.PARQUET_ROW_GROUP_SIZE_BYTES=1000) 
```

## Proposed solution
Allow `set_properties` to take in a dictionary. And also allow the dictionary value to be non-string type (similar to #469)
```
with table.transaction() as transaction: 
    transaction.set_properties({TableProperties.PARQUET_ROW_GROUP_SIZE_BYTES: 1000}) 
```

**Comment by kevinjqliu** [comment]
Another workaround can be to use 
```
with tbl.transaction() as transaction:
    transaction._apply((SetPropertiesUpdate(updates=properties),))
```

**Comment by syun64** [comment]
I think this is a great idea @kevinjqliu . Most of the table properties have `.` in the key anyways, and hence we can't pass them as kwargs anyways. Changing the input parameter to a dictionary feels a lot more straightforward.

**Comment by HonahX** [comment]
Hi @kevinjqliu @syun64 I think currently we can also set properties using dictionaries, just need `**` in front of the dictionary:
```python
properties: Dict[str, str] = {...}
with table.transaction() as transaction: 
    transaction.set_properties(**properties) 
```
This also works for properties having `.` in the key.

We do similar thing for catalog properties: [load_catalog](https://github.com/apache/iceberg-python/blob/main/pyiceberg/catalog/__init__.py#L185-L219), [example passing in glue session properties](https://github.com/apache/iceberg-python/blob/e56326d4a3ba74eb279bf57202a9121c4f2c731d/tests/catalog/test_glue.py#L602-L619)

Do you think the above way is good enough or the `**` thing is still not very intuitive for users?

**Comment by syun64** [comment]
@HonahX - yes, that's right. 

We can currently achieve functionally the same thing by providing the properties as ****properties** into the function call. I guess my point is that, if most of the properties have special characters in them so that they must be passed in as dictionary key values anyways, wouldn't it feel more straightforward for the users if we defined **properties** as a dictionary type in the first place?

Or does it still make sense to keep it as it is because something like below is possible:

```
load_catalog( "my_catalog", type="rest", uri="http://localhost:8181")
```
or
```
load_catalog( "my_catalog", type="rest", uri="http://localhost:8181", **{
            "s3.endpoint": "http://localhost:9000",
            "s3.access-key-id": "admin",
            "s3.secret-access-key": "password",
        }
```

Where users would appreciate the ability to pass in simpler catalog properties like `type` and `uri` as simple kwargs?

**Comment by kevinjqliu** [comment]
oh wow, thanks @HonahX. I didn't think to pass the properties dictionary as kwargs. 

> Do you think the above way is good enough or the ** thing is still not very intuitive for users? 

I feel like its hard to make the connection from dictionary to kwargs. And having the ability to pass the dictionary feels more 
intuitive. #503 makes it possible to pass in a dictionary to `set_properties`.


> If we finally choose to change the input parameter to dict, shall we also do the same for catalog?

I'd +1 that change. We might have to support both dictionary and kwargs to keep it backwards compatible, similar to #503


> if most of the properties have special characters in them so that they must be passed in as dictionary key values anyways, wouldn't it feel more straightforward for the users if we defined properties as a dictionary type in the first place?

+1
