### ISSUE TITLE
Add `table_exists` method to the Catalog

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#507]
### Feature Request / Improvement

Prolonging the discussion in https://github.com/apache/iceberg-python/issues/406

I think having this method on the `Catalog` would be a great addition. On top of this, we can also leverage the table-exists implementation of the REST catalog by overriding this method in the REST catalog.

**Comment by jayceslesar** [comment]
could be similar to the mkdirs api? With `exists_ok` or some param?

**Comment by Fokko** [comment]
@jayceslesar I would keep it simple by just returning a bool.

**Comment by djouallah** [comment]
@kevinjqliu  is this supported ?

`AttributeError: 'SqlCatalog' object has no attribute 'table_exists'`

**Comment by MehulBatra** [comment]
If it's open to work, I can take a shot at it!

**Comment by Fokko** [comment]
@MehulBatra That would be great 👍

**Comment by MehulBatra** [comment]
PR: https://github.com/apache/iceberg-python/pull/678

**Comment by HonahX** [comment]
Hi everyone, I think we've had the implementation. The only "issue" is that this feature hasn't been released yet. I'll add this one to 0.7.0 milestone.

@MehulBatra Thanks for the PR btw. It is good to have more tests for this feature

**Comment by Fokko** [comment]
Thanks @HonahX Let me close it for now 👍
