### ISSUE TITLE
Add metadata tables

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#511]
### Feature Request / Improvement

In Iceberg Spark there are metadata tables that provide information around the table: https://iceberg.apache.org/docs/latest/spark-queries/

The most important tables are:

- [x] *Files* assigned to @Gowthami03B, PR in https://github.com/apache/iceberg-python/pull/614
- [x] *Snapshots* assigned to @Fokko in https://github.com/apache/iceberg-python/pull/524/
- [x] *History* assigned to @ndrluis in https://github.com/apache/iceberg-python/pull/828
- [x] *Metadata log entries* @kevinjqliu (issue in https://github.com/apache/iceberg-python/issues/594): https://github.com/apache/iceberg-python/pull/667
- [x] *Manifests* @geruh: PR in https://github.com/apache/iceberg-python/pull/717
- [x] *Partitions* assigned to @syun64 (issue in https://github.com/apache/iceberg-python/issues/24)
- [x] *References* assigned to @geruh  in https://github.com/apache/iceberg-python/pull/602
- [x] *Entries* assigned to @Fokko in https://github.com/apache/iceberg-python/pull/551

**Comment by Fokko** [comment]
@Gowthami03B That would be great, any specific one that you have in mind?

**Comment by Gowthami03B** [comment]
> @Gowthami03B That would be great, any specific one that you have in mind?

Do we have a prio in mind? I jus saw your comments on https://github.com/apache/iceberg-python/issues/516, should we tackle **Files** first?

**Comment by ndrluis** [comment]
@Fokko, could you assign the History table to me?

**Comment by Fokko** [comment]
@ndrluis certainly! 👍

**Comment by syun64** [comment]
Hi @Fokko and folks, we are interested in implementing the Partitions metadata table for our use case if it hasn't been picked up already

**Comment by syun64** [comment]
Hi @Fokko could I pick up the Partitions table?

**Comment by geruh** [comment]
Hey Fokko, I'll take references here

**Comment by Fokko** [comment]
@geruh Great seeing you here again. I've assigned it to you 👍

**Comment by rahil-c** [comment]
Hey @Fokko I can try working on `Manifests` table if no one is assigned it?

**Comment by Gowthami03B** [comment]
> @Gowthami03B checking in if you're still interested in contributing the `files` table.

@Fokko yes, I will be sending over a PR shortly.

**Comment by Gowthami03B** [comment]
[https://github.com/apache/iceberg-python/pull/614](url)

**Comment by Gowthami03B** [comment]
@https://github.com/apache/iceberg-python/pull/614

**Comment by HonahX** [comment]
The last metadata table has been merged. Thanks everyone for all the great work and contributions. I think this issue can be closed
