### ISSUE TITLE
How to use pyiceberg to operate partition field and rename table

### ISSUE THREAD

**Issue by madeirak** [apache/iceberg-python#537]
### Feature Request / Improvement

1. How to use pyiceberg to add/drop/replace partition field
2. How to use pyiceberg to rename table

I used spark ddl before, but because of transaction, I want to use pyiceberg

**Comment by amogh-jahagirdar** [comment]
Hi @madeirak for partition evolution, that will be released in 0.7 but if you wanted to try it out in advance you could install from [source](https://py.iceberg.apache.org/contributing/#installation-from-source).


API docs on partition evolution: https://github.com/apache/iceberg-python/blob/main/mkdocs/docs/api.md#partition-evolution

**Comment by amogh-jahagirdar** [comment]
Renaming a table is already supported via the `catalog.rename_table` API 
https://py.iceberg.apache.org/reference/pyiceberg/catalog/#pyiceberg.catalog.Catalog.rename_table

So you'd do something like

```
from pyiceberg.catalog import load_catalog
catalog = load_catalog('your_catalog')
catalog.rename_table('db.table', 'db.renamed_table')
```

**Comment by amogh-jahagirdar** [comment]
I'm going to close this for now since the above two points should cover your use cases but please feel free to reopen in case I missed something or if you have any more questions!
