### ISSUE TITLE
Convert a StringLiteral into a DecimalLiteral

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#538]
### Feature Request / Improvement

This is not possible today, but would be nice to have in there.

**Comment by Dysprosium0626** [comment]
Hi @Fokko I'd like to have I try but I do not know where to put these code. It seems that we already have https://github.com/apache/iceberg-python/blob/bbc7e7c8d095b4afea5c27e6de324d008aa2d803/pyiceberg/expressions/literals.py#L578C1-L585C125

**Comment by syun64** [comment]
I'm making a similar observation as @Dysprosium0626 as well

```
from pyiceberg.expressions.literals import StringLiteral
from pyiceberg.types import DecimalType

StringLiteral("3.33").to(DecimalType(1, 2)).value
```

yields:

```
Decimal('3.33')
```

Is there a specific edge case we've overlooked?

**Comment by Fokko** [comment]
This indeed works:
```python
>>> from pyiceberg.types import DecimalType
>>> literal("100.00").to(DecimalType(10,2))
DecimalLiteral(Decimal('100.00'))
```

I maybe overlooked something when working on https://github.com/apache/iceberg-python/pull/539. Thanks for checking @Dysprosium0626 and @syun64 🙌
