### ISSUE TITLE
Can pyiceberg rename iceberg database?

### ISSUE THREAD

**Issue by madeirak** [apache/iceberg-python#546]
### Feature Request / Improvement

thx

**Comment by syun64** [comment]
Hi @madeirak , by "iceberg database", which one of the following are you referring to? To my knowledge, there are three levels of naming in Iceberg:

- catalog
- table namespace
- table

If you are referring to renaming a table, you can do so with the [rename_table](https://github.com/Fokko/iceberg-python/blob/f72e4f532d9e5e70bbe176fa41aa3f990ae994d0/pyiceberg/catalog/__init__.py#L362) function.

**Comment by madeirak** [comment]
thx for reply, I mean table namespace. Is there any function to rename this?

---- Replied Message ----
| From | Sung ***@***.***> |
| Date | 03/25/2024 22:37 |
| To | apache/iceberg-python ***@***.***> |
| Cc | madeirak ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [apache/iceberg-python] Can pyiceberg rename iceberg database? (Issue #546) |

Hi @madeirak , by "iceberg database", which one of the following are you referring to? To my knowledge, there are three levels of naming in Iceberg:

catalog
table namespace
table

If you are referring to renaming a table, you can do so with the rename_table function.

**Comment by syun64** [comment]
You can extend the same function to renaming the table namespace, granted that the table namespace exists.

```
properties = {##Your catalog properties##}
catalog = load_catalog("my_catalog", **properties)
# Create the namespace if it doesn't yet exist: catalog.create_namespace("new_namespace")
catalog.rename_table("old_namespace.table", "new_namespace.table")
```
