### ISSUE TITLE
Add samples for listing table.files and table.partitions

### ISSUE THREAD

**Issue by moryachok** [apache/iceberg-python#578]
### Question

After examining your documentation, I couldn't locate the methods to list a table's partitions or its data files. Could you please provide relevant examples or consider adding this capability if it's not currently available?

**Comment by Fokko** [comment]
Hey @moryachok Thanks for raising this. This is currently being worked on in https://github.com/apache/iceberg-python/issues/511 

The files one should be rather straightforward since that's also supported through the CLI: `pyiceberg files database.table`

**Comment by Fokko** [comment]
@moryachok It looks like someone else is already working on files, how about partitions? I'll merge https://github.com/apache/iceberg-python/pull/551 later today and then it should be relative straightforward.
