### ISSUE TITLE
[feat request] Add `metadata_log_entries` metadata table

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#594]
### Feature Request / Improvement

Similar to the Spark metadata table
https://iceberg.apache.org/docs/nightly/spark-queries/#metadata-log-entries

which uses the `metadata-log` field in the Table's Metadata (See https://iceberg.apache.org/spec/#table-metadata-fields)

**Comment by Fokko** [comment]
Thanks for creating this issue @kevinjqliu, I've also assigned you in https://github.com/apache/iceberg-python/issues/511
