### ISSUE TITLE
[BUG] string row filter ignore 2nd (and onwards) And

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg-python#64]
### Apache Iceberg version

None

### Please describe the bug 🐞

```
tasks = table.scan(row_filter="dt='2023-08-20' AND view_type=1 AND hr='00' ").plan_files()
```
Only filter for `dt` and `view_type` is taken care of, but `hr` is not.

**Comment by amogh-jahagirdar** [comment]
Hm yeah I can repro this with a simple test in `table/test_init.py`

```
  scan = table.scan(row_filter="x=1 AND y=1 AND z=1")
  assert scan.row_filter == And(EqualTo("x", 1), EqualTo("y", 1), EqualTo("z", 1))
```

this fails the assertion because the  row filter ends up being And(EqualTo("x", 1), EqualTo("y", 1)) for some reason.

**Comment by amogh-jahagirdar** [comment]
Looking into this

**Comment by amogh-jahagirdar** [comment]
https://github.com/apache/iceberg-python/blob/main/pyiceberg/expressions/parser.py#L236 this is where it'll skip anything after. I think this needs to combine all results in a single And (same applies for Or). But I need to do some testing with different combinations, not sure what how PyParse actually passes in the ParseResults when it visits the expression
