### ISSUE TITLE
`pylintrc` still needed? 

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#666]
### Question

Pylint was removed in favor of ruff 
https://github.com/apache/iceberg-python/commit/5445fde3ac2b1c1ca3a5d96a41809fd62304129b#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9L64-L68

Is the `pylintrc` file still needed? 
https://github.com/apache/iceberg-python/blob/main/pylintrc

**Comment by Fokko** [comment]
No, the `pylintrc` can go 👍
