### ISSUE TITLE
Failing to create a table using pyiceberg

### ISSUE THREAD

**Issue by salexln** [apache/iceberg-python#692]
### Question

I running this code

```python
glue_database_name = "alex_iceberg_test_db"
glue_catalog_uri = "s3://alex-iceberg-test-storage"
my_namespace = 'alex_db'


# Instantiate glue catalog
catalog = load_catalog("glue", **{"type": "glue", 
                                  "s3.region": "region", 
                                  "profile": "ALEX",
                                  "s3.access-key-id": "XXX",
                                  "s3.secret-access-key": "YYY"})


# Define the Iceberg schema
schema = Schema(
    NestedField(field_id=1, name="data", field_type=StringType(), required=False)        
)


## Create the Iceberg table using the Iceberg catalog
table_name = 'test_1'
catalog.create_table(
    identifier=f'{my_namespace}.{table_name}',
    location=glue_catalog_uri,
    schema=schema
)
```

and getting that 
```
OSError: When getting information for key 'metadata/00000-5df640cc-b47c-4b39-b578-07113565dab5.metadata.json' in bucket 'alex-iceberg-test-storage': AWS Error ACCESS_DENIED during HeadObject operation: No response body.
```

Inside `alex-iceberg-test-storage` I do have `metadata` but the `00000-5df640cc-b47c-4b39-b578-07113565dab5.metadata.json` is not there. 
Why does it searching for that file and who should create it?

**Comment by syun64** [comment]
Hi @salexln - the "ACCESS_DENIED" error in the log trace you provided gives me the impression that you don't have HeadObject permissions in alex-iceberg-test-storage bucket for the tenancy you are using. Could you double check your bucket policy?

```
OSError: When getting information for key 'metadata/00000-5df640cc-b47c-4b39-b578-07113565dab5.metadata.json' in bucket 'alex-iceberg-test-storage': AWS Error ACCESS_DENIED during HeadObject operation: No response body.
```

**Comment by salexln** [comment]
@syun64 
Does it try to write `00000-5df640cc-b47c-4b39-b578-07113565dab5.metadata.json'  file or read? If it is trying to write, than you might be right and this is permission issue, but I think it is trying to read, and this file does not exist.

**Comment by syun64** [comment]
@salexln 
I think in order to write it, it uses `head_object` to check if the file exists first:

https://github.com/apache/iceberg-python/blob/da313d011198028970f9301b730cbc22fe613b36/pyiceberg/io/pyarrow.py#L301C39-L301C45

**Comment by felixscherz** [comment]
Hi, I just tried this on my machine, could you double check the properties that you pass to `load_catalog`. I believe the glue catalog looks for the AWS profile name under `profile_name` instead of `profile` (see  [`GlueCatalog`](https://github.com/apache/iceberg-python/blob/7bd5d9e6c32bcc5b46993d6bfaeed50471e972ae/pyiceberg/catalog/glue.py#L280-L295)). 
This works for me after setting up an S3 bucket and a glue database:
```python
# Instantiate glue catalog
catalog = load_catalog(
    "glue",
    **{
        "type": "glue",
        "s3.region": "<region>",
        "s3.access-key-id": "<access-key>",
        "s3.secret-access-key":"<secret-key>",
        "profile_name": "<aws-profile-name>"
    },
)
```

**Comment by ArijitSinghEDA** [comment]
Hello all, I am facing the same issue when trying to use SQL Catalog with PostgreSQL.
```
catalog = load_catalog(
        "default",
        **{
            "type": "sql",
            "uri": "postgresql+psycopg2://user:password@0.0.0.0:5432/iceberg",
            "s3.endpoint": "0.0.0.0:9000",
            "py-io-impl": "pyiceberg.io.pyarrow.PyArrowFileIO",
            "s3.access-key-id": "admin",
            "s3.secret-access-key": "password",
            "s3.region": "us-east-1"
        }
    )


catalog.create_table(
            identifier="ns.table",
            schema=schema,
            location=f"s3a://warehouse/ns/tbl"
        )
```
