### ISSUE TITLE
Support `snapshot_properties` argument for `add_files` function

### ISSUE THREAD

**Issue by enkidulan** [apache/iceberg-python#694]
### Feature Request / Improvement

It would be great to make the interface more aligned with `append` and `overwrite` function, which support `snapshot_properties` argument. The logic also seems simple enough to support the feature.

**Comment by Fokko** [comment]
@enkidulan Thanks for raising this, and I agree! Are you interested in contributing to this feature?

**Comment by enkidulan** [comment]
I've created a draft PR - https://github.com/apache/iceberg-python/pull/695
