### ISSUE TITLE
Support `register_table` in GlueCatalog

### ISSUE THREAD

**Issue by rmn36** [apache/iceberg-python#705]
### Feature Request / Improvement

`register_table` is currently the only Catalog method not implemented https://github.com/apache/iceberg-python/blob/main/pyiceberg/catalog/glue.py#L407
Also the docs are misleading because this method is shown in the docs and doesn’t have any note about not being implemented https://py.iceberg.apache.org/reference/pyiceberg/catalog/glue/#pyiceberg.catalog.glue.GlueCatalog.register_table

**Comment by MehulBatra** [comment]
I would love to take a shot at it.

**Comment by MehulBatra** [comment]
Initial Progress: https://github.com/apache/iceberg-python/pull/711

**Comment by kevinjqliu** [comment]
Completed in #711
