### ISSUE TITLE
Snowflke can't read tables generated by pyicberg ?

### ISSUE THREAD

**Issue by djouallah** [apache/iceberg-python#723]
### Question

I keep getting this error ?

`Failed to read from Iceberg file 'abfss://xxxxxx.dfs.core.windows.net/data/iceberg_dwh/scada/metadata/snap-2728627078701324745-0-7c1d442e-7321-46f8-aa06-5d5f94cde607.avro': Failed to open file: abfss://xxxxxx.dfs.core.windows.net/data/iceberg_dwh/scada/metadata/snap-2728627078701324745-0-7c1d442e-7321-46f8-aa06-5d5f94cde607.avro`

**Comment by djouallah** [comment]
@Fokko  thanks  adding "legacy-current-snapshot-id": True fix it

**Comment by djouallah** [comment]
i see, it is an upstream issue
https://github.com/apache/iceberg/issues/10127

**Comment by sfc-gh-dhuo** [comment]
Normally the abfss URI is expected to look like this, according to [azure docs](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction-abfs-uri):

    abfs[s]://<file_system>@<account_name>.dfs.core.windows.net/<path>/<file_name>
    
In your example, did your files contain the `<file_system>` component of the URI? (Or what would be the "container" in Azure Blob syntax)

**Comment by djouallah** [comment]
the URI  is `'abfss://account_name.dfs.core.windows.net/data/iceberg_dwh/scada/metadata/snap-2728627078701324745-0-7c1d442e-7321-46f8-aa06-5d5f94cde607.avro'`

btw it works with BigQuery
