### ISSUE TITLE
Improve readme for pyiceberg

### ISSUE THREAD

**Issue by MehulBatra** [apache/iceberg-python#774]
### Feature Request / Improvement

We have an amazing document, but a readme can help alongside, without leaving GitHub, you will get the best of both worlds.

I would like to highlight some of the benefits that we yield out of it

- Improved Accessibility: Quickly understand and set up the project.
- Enhanced Collaboration: Encourages contributions with clear guidelines.
- Better Support: Provides self-help resources for users.
- Promotion: Improves project visibility and discoverability.
- Effective Management: Aligns contributors with the project’s vision.
- Educational Value: Serves as a learning resource for best practices.

I have some ideas around the same.

**Comment by MehulBatra** [comment]
@Fokko @HonahX @kevinjqliu what are your thoughts about this?

**Comment by kevinjqliu** [comment]
Great suggestion! It'll be good to balance contents between the README and the pyiceberg website (https://py.iceberg.apache.org/)
