### ISSUE TITLE
Add anchors to sections in "Configuration" documentation page

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#808]
### Feature Request / Improvement

I would like to refer to a specific section of the configuration documentation (https://py.iceberg.apache.org/configuration/) 
For example, I want to link the "FileIO" section of the doc. 

This can be done by modifying the markdown page (https://github.com/apache/iceberg-python/blob/main/mkdocs/docs/configuration.md)

**Comment by Anirudh-Narra** [comment]
other than the FileIO section what other sections can be changed .

**Comment by kevinjqliu** [comment]
Ideally, all the headers and subheaders can be anchored.

GitHub markdown provides this functionality:
https://github.com/apache/iceberg-python/blob/main/mkdocs/docs/configuration.md#fileio
https://github.com/apache/iceberg-python/blob/main/mkdocs/docs/configuration.md#s3

**Comment by uatach** [comment]
@kevinjqliu hello, I would like to help with this
