### ISSUE TITLE
[BUG] to_arrow conversion does not support iceberg table column name containing slash

### ISSUE THREAD

**Issue by puchengy** [apache/iceberg-python#81]
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

PR to reproduce https://github.com/puchengy/iceberg-python/commit/68081491641b0d7bada13a18b98ded3e08e127a6

```
 pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(letter/abc) in letter_x2Fabc: string not null
```
The issue seems to be when writing parquet from Spark, we sanitized the name to follow the avro spec.

I think we should make some changes in `_task_to_table` function:
1. Use sanitized column name for projection when interacting with pyarrow as that is the actual names stored on parquet files.
2. Before returning pyarrow table, we should rename the columns back to right iceberg correct column name based one the parquet field id.

**Comment by Fokko** [comment]
Great catch @puchengy I wasn't aware of this sanitization behavior. Do you want to write a patch for it?

**Comment by Fokko** [comment]
Thanks for fixing this @puchengy
