### ISSUE TITLE
[Feature] Support Metadata Log Update For Non-Rest Catalogs

### ISSUE THREAD

**Issue by HonahX** [apache/iceberg-python#849]
### Feature Request / Improvement

Currently, the `update_table_metadata` used by non-rest catalogs does not update `metadata_log` field when applying table updates. It will be great to add this feature to unlock utils such as https://github.com/apache/iceberg-python/pull/667

Ref:

- [Metadata Log Field](https://iceberg.apache.org/spec/#table-metadata-fields)
- [Java Code Ref](https://github.com/apache/iceberg/blob/8248663a2a1ffddd2664ea37b45882455466f71c/core/src/main/java/org/apache/iceberg/TableMetadata.java#L1445-L1452)

**Comment by soumya-ghosh** [comment]
@HonahX @kevinjqliu  I would like to work on this one.

**Comment by soumya-ghosh** [comment]
PR for review - https://github.com/apache/iceberg-python/pull/977

**Comment by kevinjqliu** [comment]
Closed by #977
