### ISSUE TITLE
distutils removed in Python >= 3.12

### ISSUE THREAD

**Issue by noahseger** [apache/iceberg-python#859]
### Apache Iceberg version

None

### Please describe the bug 🐞

So this crashes in latest Python https://github.com/apache/iceberg-python/blob/a6cd0cf325b87b360077bad1d79262611ea64424/pyiceberg/utils/config.py#L19C28-L19C37

**Comment by Fokko** [comment]
cc @MehulBatra

**Comment by MehulBatra** [comment]
Adding a function with the same name in the types.py to replace the distutil dependency, as Python 3.12 no longer support the distutil package.
