### ISSUE TITLE
Optional Schema Check for `add_files`

### ISSUE THREAD

**Issue by syun64** [apache/iceberg-python#869]
### Feature Request / Improvement

Many folks have been reaching out about the usage of [add_files](https://github.com/apache/iceberg-python/blob/main/pyiceberg/table/__init__.py#L542), which is a sign that there's a market for users who would prefer not to rewrite parquet files and just want to side load them into an Iceberg table.

Although it is noted to be an expert user feature in the documentation (as is the case with the rest of migration procedures Iceberg has had) the ease of use of the feature seems to be appealing to users of all levels.

Therefore, I think it would be great to introduce optional guardrails for the API.

Introducing an optional [schema check](https://github.com/apache/iceberg-python/blob/main/pyiceberg/table/__init__.py#L160) would be an easy first step.

**Comment by Fokko** [comment]
@syun64 What do you think of enabling the schema validation, and having the ability to turn it off? Adding a file to a table might potentially brick a table if I understand the implication correctly.

**Comment by syun64** [comment]
Yes, that was what I was thinking as well.
