### ISSUE TITLE
Rename `data_sequence_number` to `sequence_number`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#893]
### Feature Request / Improvement

It looks like a misnamed field slipped in:

```json
{
    "status": 1,
    "snapshot_id": {
        "long": 898025966831056900
    },
    "data_sequence_number": null,
    "file_sequence_number": null,
    "data_file": {
        "content": 0,
        "file_path": "/tmp/some.db/tablev2/data/00000-0-93717a88-1cea-4e3d-a69a-00ce3d087822.parquet",
        "file_format": "PARQUET",
        "partition": {},
        "record_count": 3,
        "file_size_in_bytes": 5459,
        "column_sizes": { ... },
        "value_counts": { ... },
        "null_value_counts": { ... },
        "nan_value_counts": { ... },
        "lower_bounds": { ... },
        "upper_bounds": { ... },
        "key_metadata": null,
        "split_offsets": {
            "array": [
                4
            ]
        },
        "equality_ids": null,
        "sort_order_id": null
    }
}
```

This should be `sequence_number`:

![image](https://github.com/apache/iceberg-python/assets/1134248/90e4ca9c-a38f-4fd4-a031-7a4c8f02b574)

Luckily this still worked due to Iceberg's field-id based lookup, but would be good to get this cleaned up.

Relevant code:

https://github.com/apache/iceberg-python/blob/a8d3f17d42b00b507a3522714fe431a18124493e/pyiceberg/manifest.py#L380

**Comment by kevinjqliu** [comment]
Is there a way on the Java/spark side to turn metadata information into JSON? With #535, perhaps we can compare the two JSON results and check for mismatches like this one.

**Comment by soumya-ghosh** [comment]
@Fokko I would like to take a shot at this one.

**Comment by Fokko** [comment]
@soumya-ghosh Feel free to take a stab at it, let me know if you run into anything

**Comment by Fokko** [comment]
> Is there a way on the Java/spark side to turn metadata information into JSON? With https://github.com/apache/iceberg-python/issues/535, perhaps we can compare the two JSON results and check for mismatches like this one.

That would be an interesting idea. We could take the PySpark schema and turn it into an Iceberg schema and compare the two (or just compare the Avro schemas)

**Comment by soumya-ghosh** [comment]
@Fokko the PR https://github.com/apache/iceberg-python/pull/900 is ready for review.
