### ISSUE TITLE
Move `_determine_partitions` to `pyarrow.py`

### ISSUE THREAD

**Issue by Fokko** [apache/iceberg-python#896]
### Feature Request / Improvement

It relies heavily on PyArrow, so it should be in `pyarrow.py` as suggested by @HonahX in https://github.com/apache/iceberg-python/pull/569#discussion_r1659979992

**Comment by soumya-ghosh** [comment]
@Fokko could I pick this up?

**Comment by Fokko** [comment]
@soumya-ghosh Sure thing! 🙌

**Comment by soumya-ghosh** [comment]
@Fokko PR https://github.com/apache/iceberg-python/pull/906 is ready for review.
