### ISSUE TITLE
UncheckedSQLException while deleting table

### ISSUE THREAD

**Issue by ArijitSinghEDA** [apache/iceberg-python#901]
### Question

I am running a delete command like this:

```
# catalog is already loaded

catalog.drop_table("ns.tbl")
```

I am facing the following error:

```
pyiceberg.exceptions.ServerError: UncheckedSQLException: Failed to execute: DELETE FROM iceberg_tables WHERE catalog_name = ? AND table_namespace  = ? AND table_name = ? AND (iceberg_type = 'TABLE' OR iceberg_type IS NULL)
```

I am using `pyiceberg==0.6.1`

**Comment by kevinjqliu** [comment]
Thanks for the report! 

Do you mind adding a code snippet to help reproduce this issue? 
It looks like this is related to the SQL Catalog `drop_table` function
https://github.com/apache/iceberg-python/blob/7dff359e0515839fbe24fac2108dcb2d64694b7a/pyiceberg/catalog/sql.py#L295

**Comment by ArijitSinghEDA** [comment]
Hi @kevinjqliu 

On further investigation, it was a problem with the standalone iceberg server. It has been rectified now.

Thank you for taking out your time.
