### ISSUE TITLE
How to get one table partition values without doing a query, from metadata

### ISSUE THREAD

**Issue by doctormohamed** [apache/iceberg-python#916]
### Question

I need to get a table partitions values like spark iceberg does:

![image](https://github.com/apache/iceberg-python/assets/60315717/186350c7-0201-4db7-bb0e-d802d99f2915)

I wasnt able to find a way to get that from the table instance itself.

catalog = pyiceberg.catalog.load_catalog(
    'AwsGlueCatalog', **{"type": "glue"}
)
table = catalog.load_table('db.table')

**Comment by doctormohamed** [comment]
@kevinjqliu any toughts on this?

**Comment by kevinjqliu** [comment]
Looks like you're looking for the `partitions` metadata table. 
https://iceberg.apache.org/docs/latest/spark-queries/#partitions

Here's how you can do the same in pyiceberg
https://github.com/apache/iceberg-python/blob/main/mkdocs/docs/api.md#partitions

This is based on the latest changes in the repo and will be available in the 0.7.0 release. 

In the meantime, you can use it if you install `pyiceberg` using the github repo to get the latest code.
