### ISSUE TITLE
Support loading custom catalog implementation

### ISSUE THREAD

**Issue by jackye1995** [apache/iceberg-python#938]
### Feature Request / Improvement

We have a customer asking about the ability to load a custom catalog implementation, similar to how Java Iceberg works today by loading a custom Java class path. The customer understands that the community would like to go with REST catalog in general, but they are not ready to onboard to that yet for at least a year or two.

I see [something similar](https://github.com/apache/iceberg-python/blob/20f6afdf5f000ea5b167e804012f2000aa5b8573/pyiceberg/io/__init__.py#L294-L305) done in FileIO path. What is our general thoughts around this topic? Are we open to add similar support for catalog when doing [`load_catalog`](https://github.com/apache/iceberg-python/blob/1ed3abdd1aec480911eeec4f0f46a04efe53dc06/pyiceberg/catalog/__init__.py#L195)?

**Comment by jackye1995** [comment]
cc @Fokko @HonahX @syun64 @kevinjqliu

**Comment by kevinjqliu** [comment]
I like the option to load a custom catalog implementation. As long as the implementation subclasses [Catalog](https://github.com/apache/iceberg-python/blob/1ed3abdd1aec480911eeec4f0f46a04efe53dc06/pyiceberg/catalog/__init__.py#L277) and have all the necessary functions implemented. We would also add a new ([CatalogType](https://github.com/apache/iceberg-python/blob/1ed3abdd1aec480911eeec4f0f46a04efe53dc06/pyiceberg/catalog/__init__.py#L104))

It'll be great if we have a set of tests to encode specific catalog behaviors, similar to #813

On a meta level, the customer can also "wrap" their custom catalog implementation with the REST protocol. Similar to how the [iceberg-rest-image](https://github.com/tabular-io/iceberg-rest-image/blob/master/src/main/java/org/apache/iceberg/rest/RESTCatalogServer.java#L88) is implemented

**Comment by jackye1995** [comment]
> the customer can also "wrap" their custom catalog implementation with the REST protocol. Similar to how the [iceberg-rest-image](https://github.com/tabular-io/iceberg-rest-image/blob/master/src/main/java/org/apache/iceberg/rest/RESTCatalogServer.java#L88) is implemented

Yes we brought up that solution, but they do not want to maintain this additional layer of indirection that could cause additional availability, latency, security issues.

**Comment by syun64** [comment]
Hi @jackye1995 - I'm of the opinion that this is totally fine. If the client wants to have their own catalog implementation for any of many possible reasons (e.g. because it requires a specific auth mechanism) they should be allowed to.

I'm actually wondering what about the state of code right now, that would prevent them from having their own implementation. I want to hold off on giving a definite answer before actually trying this out, but I think even now, they should be able to implement the `Catalog` or `MetastoreCatalog` classes and use their own Catalog. In that case, maybe adding a bit more documentation on the topic to explain how they can go about implementing their own `Catalog`s will be helpful to the users.

**Comment by Fokko** [comment]
Yes, I think that would be a nice addition. As Jack already pointed out, we already have dynamic loading of file-io's using `py-io-impl`, so loading a catalog would be relatively easy to add 👍 

You could also inherit from an existing catalog if you want to extend certain parts of it (for example, the authentication mechanism as Sung pointed out). All for it 👍

**Comment by jackye1995** [comment]
I can give a try for it, assigning to myself.

**Comment by jayceslesar** [comment]
Would it hurt to add some checks to the custom catalog implementation passed in to ensure that a core suite of methods are provided in the custom implementation?  I can imagine a user creating a custom catalog with not everything implemented and really shooting themselves in the foot. I suppose why not enforce the custom catalog inherit from the abstract `Catalog` class?

**Comment by jackye1995** [comment]
The type hint `def _import_catalog(name: str, catalog_impl: str, properties: Properties) -> Optional[Catalog]:` suggests that it should inherit the `Catalog` class, but it is not enforced at this moment. Are you suggesting to add a check to enforce that?

Personally speaking I prefer to not check it. I see it as an advantage of Python vs strictly typed languages like Java to allow not inheriting a interface during dynamic loading, so it is more flexible for people that could leverage it. But I would imagine most people with custom implementation is inheriting the `Catalog` class anyway.
