### ISSUE TITLE
Metadata field `last-updated-ms` is not updated for DDL operations

### ISSUE THREAD

**Issue by soumya-ghosh** [apache/iceberg-python#948]
### Apache Iceberg version

main (development)

### Please describe the bug 🐞

Executing DDL operations on Iceberg table using Pyiceberg is not updating `last-updated-ms` field in metadata file.
`last-updated-ms` field is updated correctly when using RestCatalog, but it is not updated when using GlueCatalog, SqlCatalog (and possibly HiveCatalog as well).
Sequence of operations/updates:
- Create table
- Append data
- Update schema - Add a column / add description for a column
- Set a table property

Although new metadata file is generated for each update, last-updated-ms is not updated when changes are limited to metadata file only.

Sample code:

```python
catalog = load_catalog("glue", **glue_catalog_conf)
table = catalog.create_table(
    "namespace.table1",
    schema=Schema(
        NestedField(1, "city", StringType(), required=False),
        NestedField(2, "lat", DoubleType(), required=False),
        NestedField(3, "long", DoubleType(), required=False),
    ),
)

df = pa.Table.from_pylist(. . .)
table.append(df)

with table.update_schema() as update:
    update.add_column("country", StringType(), required=False)

with table.transaction() as txn:
    txn.set_properties({"abc": "def"})
```

**Comment by kevinjqliu** [comment]
Great catch! According to the spec, https://iceberg.apache.org/spec/#table-metadata-fields
```
last-updated-ms	
Timestamp in milliseconds from the unix epoch when the table was last updated. Each table metadata file should update this field just before writing.
```

All the catalog implementations should exhibit this behavior. As you mentioned, it should be updated for write operations, DDL, and DML operations.

**Comment by soumya-ghosh** [comment]
I can work on this one.
@kevinjqliu please assign this issue to me.

**Comment by soumya-ghosh** [comment]
Raised PR https://github.com/apache/iceberg-python/pull/956
