### ISSUE TITLE
[documentation] library version upgrade fails `test_version_format`

### ISSUE THREAD

**Issue by kevinjqliu** [apache/iceberg-python#949]
### Feature Request / Improvement

When Pyiceberg upgrades its version, such as now from `0.6.1` -> `0.7.0`. The local repo will fail `test_version_format` until the library is reinstalled with the new version.

Add explanation to [`test_version_format`](https://github.com/apache/iceberg-python/blob/d8bc1ca9af7957ce4d4db99a52c701ac75db7688/tests/test_version.py#L21) error message that the failure can be due to the Pyiceberg library version bump and possible solution such as to rerun `make install`.

```
================================================================== FAILURES ==================================================================
____________________________________________________________ test_version_format _____________________________________________________________

    def test_version_format() -> None:
        from importlib import metadata
    
        installed_version = metadata.version("pyiceberg")
    
>       assert (
            __version__ == installed_version
        ), f"{__version__} <> {installed_version}, the installed version does not match with the current codebase"
E       AssertionError: 0.7.0 <> 0.6.1, the installed version does not match with the current codebase
E       assert '0.7.0' == '0.6.1'
E         - 0.6.1
E         + 0.7.0

tests/test_version.py:26: AssertionError
```

**Comment by laksh-krishna-sharma** [comment]
May I work on this issue with a little bit of your guidance?

**Comment by kevinjqliu** [comment]
sure @laksh-krishna-sharma , assigned to you. Please let me know if you have any questions

**Comment by laksh-krishna-sharma** [comment]
Thank you, @kevinjqliu. I will start working on it immediately. I will reach out if I have any questions.
