### ISSUE TITLE
Prevent `add_files` from adding a file that's already referenced by the Iceberg Table

### ISSUE THREAD

**Issue by sungwy** [apache/iceberg-python#998]
### Feature Request / Improvement

Currently `add_files` doesn't have a check to prevent adding an object that's already referenced by the Iceberg Table.

We should include these two checks to prevent bad behaviors of adding an already referenced data file as a new manifest entry. 

We could do this by running the following two checks before the file addition:
1. First check that the list of `file_paths` is unique
2. Check that all the files in the `file_paths` aren't referenced by any of the manifests in the current snapshot of the Iceberg Table.

**Comment by amitgilad3** [comment]
Hey, im new to the pyiceberg but would love to take take a crack at this

**Comment by sungwy** [comment]
Hi @amitgilad3 sounds great! I'll get this assigned to you. Please let me know if you'd like some pointers :)

**Comment by amitgilad3** [comment]
Hey @sungwy - just created my first pr #1036 , would really appreciate your review and if you have any suggestions or if i choose the wrong place to implement my checks.
